(()=>{
const $=s=>document.querySelector(s),app=document.getElementById('app');
const H=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORE='rd-suite-progress-v1';
const modules=[
 ['abcde','🩺','ABCDE-Training','Strukturierte Untersuchung Schritt für Schritt'],
 ['dokumentation','📋','Einsatzdokumentation','Einsatz, Patient, Befunde und Übergabe erfassen'],
 ['medlernen','💊','Medikamenten-Lernen','Karteikarten, Wissen und Mini-Quiz'],
 ['gefahren','🦺','Gefahren & Eigenschutz','Lagegefahren erkennen und absichern'],
 ['psychiatrie','🧠','Psychiatrische Einsatzlagen','Kommunikation, Lageeinschätzung und Eigenschutz'],
 ['ausbildung','🎓','Ausbildungsmodus','Lernpfad mit Modulen und Fortschritt'],
 ['pruefung','🏆','Prüfungsmodus','Fall- und Wissensfragen mit Auswertung'],
 ['wissensdatenbank','📚','Wissensdatenbank','Zentrale Suche über Lerninhalte'],
 ['suche','🔎','Globale Suche','Ein Einstieg für alle Inhalte'],
 ['statistik','📊','Statistik & Fortschritt','Lernstand, Ergebnisse und Verlauf']
];
const knowledge=[
 ['ABCDE','ABCDE','Strukturierte Ersteinschätzung von A bis E. Im Training werden Befunde schrittweise erhoben.'],
 ['Airway','ABCDE','A fokussiert auf Atemweg, Schutzreflexe, sichtbare Obstruktion und relevante Hinweise.'],
 ['Breathing','ABCDE','B umfasst Atemarbeit, Atemfrequenz, Oxygenierung und klinische Zeichen der Atmung.'],
 ['Circulation','ABCDE','C umfasst Puls, Hautzeichen, Blutdruck, Blutung und Perfusionshinweise.'],
 ['Disability','ABCDE','D umfasst Bewusstsein, neurologische Auffälligkeiten und reversible Ursachen.'],
 ['Exposure','ABCDE','E betrachtet den Gesamteindruck, Verletzungen, Temperatur und Umfeld.'],
 ['Eigenschutz','Sicherheit','Vor Patientenkontakt Lage, Gefahren, Fluchtweg, PSA und benötigte Kräfte prüfen.'],
 ['Verkehrsunfall','Sicherheit','Verkehr, Airbags, Fahrzeugstabilität, Kraftstoff, Hochspannung und weitere Gefahren berücksichtigen.'],
 ['Gasgeruch','Sicherheit','Gefahrenbereich nicht unnötig betreten, Eigenschutz priorisieren und zuständige Kräfte nach lokalem Ablauf nachfordern.'],
 ['Aggressive Person','Psychiatrie','Abstand, Ausweg, ruhige Kommunikation, Umfeld und Unterstützung beachten.'],
 ['Akute Psychose','Psychiatrie','Reizarm, respektvoll und klar kommunizieren; nicht konfrontativ argumentieren und Eigenschutz beachten.'],
 ['Suizidale Krise','Psychiatrie','Akute Eigengefährdung ernst nehmen, Lage sichern und nach lokalem Krisen-/Notfallablauf handeln.'],
 ['Intoxikation','Psychiatrie','Substanz, Zeitpunkt, Menge und Begleitstoffe systematisch erheben; Bewusstsein und Vitalfunktionen beobachten.'],
 ['Dokumentation','Dokumentation','Zeitpunkte, Beschwerden, Befunde, Vitalwerte, Maßnahmen, Verlauf und Übergabe nachvollziehbar dokumentieren.'],
 ['Übergabe','Dokumentation','Strukturiert, kurz und vollständig: Problem, relevante Befunde, Verlauf und bereits erfolgte Maßnahmen.'],
 ['Vitalwerte','Diagnostik','Vitalwerte sind Momentaufnahmen und sollen im Verlauf erneut bewertet und dokumentiert werden.'],
 ['Bewusstsein','Diagnostik','Bewusstseinslage strukturiert beobachten und Veränderungen zeitnah dokumentieren.'],
 ['Schmerz','Diagnostik','Schmerz mit standardisierter Skala erfassen und im Verlauf erneut bewerten.'],
 ['Anaphylaxie','Notfallbild','Akute allergische Reaktion mit möglicher Beteiligung von Atemweg, Atmung und Kreislauf; lokale SOP beachten.'],
 ['Thoraxschmerz','Notfallbild','Thoraxschmerz strukturiert nach Beginn, Charakter, Begleitsymptomen und Verlauf beurteilen.'],
 ['Dyspnoe','Notfallbild','Atemnot systematisch nach Schwere, Beginn, Auslösern und Begleitzeichen erfassen.'],
 ['Schlaganfall','Notfallbild','Neurologischen Ausfall, Zeitpunkt/letzte sichere Normalität und Verlauf dokumentieren.'],
 ['Hypoglykämie','Notfallbild','Bewusstseinsveränderung und Glukosewert im Kontext betrachten; lokale Abläufe anwenden.'],
 ['MANV','Einsatzführung','Bei mehreren Verletzten Sichtung, Führung, Kommunikation und Ressourcen nach lokalem Konzept strukturieren.'],
 ['Hygiene','Sicherheit','Handhygiene, PSA und situationsgerechte Kontaminationsvermeidung gehören zu jedem Einsatz.'],
 ['Prüfungsvorbereitung','Ausbildung','Fälle bearbeiten, Fehler analysieren und schwache Themen gezielt wiederholen.']
];
const psychCases=[
 {title:'Akute Unruhe im Wohnraum',risk:'Mittel',facts:['Patient laut und angespannt','eine Angehörige vor Ort','kein sicherer Fluchtweg direkt hinter dem Patienten'],choices:[['Allein und dicht herantreten','Risiko erhöhen'],['Abstand, Ausgang sichern und Unterstützung organisieren','Sicherheitsorientierter Ansatz'],['Patient sofort körperlich fixieren','Nicht als Standardmaßnahme'] ]},
 {title:'Paranoide Wahrnehmung',risk:'Hoch',facts:['Patient überzeugt, verfolgt zu werden','spricht schnell','keine sichtbare Waffe'],choices:[['Konfrontativ beweisen, dass die Wahrnehmung falsch ist','Eher deeskalierend vermeiden'],['Ruhig bleiben, Abstand und Ausweg sichern','Sinnvoller Kommunikationsansatz'],['Mehrere Personen gleichzeitig einreden','Kann Überforderung verstärken']]},
 {title:'Suizidale Krise',risk:'Hoch',facts:['Patient äußert konkrete Suizidgedanken','Zugang zu potenziell gefährlichen Gegenständen im Raum','Angehörige warten draußen'],choices:[['Gefahr ignorieren und nur Symptome dokumentieren','Unzureichend'],['Eigenschutz/Lage sichern, Unterstützung nachfordern und lokalem Krisenablauf folgen','Prioritär'],['Patienten allein lassen','Nicht sicher']]}
];
const hazardCases=[
 {title:'Verkehrsunfall auf Landstraße',hazards:['fließender Verkehr','instabiles Fahrzeug','Glassplitter'],answer:'Verkehr sichern, Abstand halten und nötige Einsatzkräfte/Absicherung nachfordern.'},
 {title:'Unbekannter Stoff im Keller',hazards:['unkannter Stoff','schlechter Zugang','mögliche Dämpfe'],answer:'Nicht ungeschützt vorgehen; Gefahrenbereich beachten, Eigenschutz/PSA und zuständige Gefahrstoffkräfte einbeziehen.'},
 {title:'Stromunfall in Werkstatt',hazards:['elektrische Energie','Maschinen','enge Umgebung'],answer:'Stromquelle/Abschaltung und sichere Annäherung nach lokalem Verfahren priorisieren; nicht in den Gefahrenbereich greifen.'},
 {title:'Aggressive Person im öffentlichen Raum',hazards:['Fremdgefährdung','Publikum','unklare Bewaffnung'],answer:'Abstand, Rückzugsweg und Unterstützung/Polizei nach Lage priorisieren.'},
 {title:'Wohnungsbrand',hazards:['Rauch','Hitze','unübersichtlicher Innenraum'],answer:'Eigenschutz und Feuerwehrlage priorisieren; keine ungesicherte Rettungsaktion aus dem Gefahrenbereich.'}
];
const abcdeSteps=[
 ['A – Airway','Atemweg prüfen','Was muss bei Atemweg und Schutzreflexen beobachtet werden?',['frei / unauffällig','auffällig / gefährdet','unklar'] ],
 ['B – Breathing','Atmung beurteilen','Welche Befunde gehören zur strukturierten Atembeurteilung?',['Atemfrequenz und Atemarbeit','nur Hautfarbe','nur Blutdruck'] ],
 ['C – Circulation','Kreislauf beurteilen','Welche Angaben helfen bei der Kreislaufbeurteilung?',['Puls, Blutdruck, Haut und Blutung','nur Temperatur','nur Pupillen'] ],
 ['D – Disability','Bewusstsein/Neurologie','Welche Information ist besonders wichtig?',['Bewusstseinslage und neurologische Auffälligkeiten','nur Körpergröße','nur Gewicht'] ],
 ['E – Exposure','Gesamtuntersuchung','Was ergänzt die Untersuchung?',['Verletzungen, Temperatur und Umfeld','nur Puls','nur Medikamentenname'] ]
];
function state(){try{return Object.assign({done:{},abcde:0,quizCorrect:0,quizTotal:0,examBest:0,docs:0,cases:0},JSON.parse(localStorage.getItem(STORE)||'{}'))}catch(e){return {done:{},abcde:0,quizCorrect:0,quizTotal:0,examBest:0,docs:0,cases:0}}}
function save(s){localStorage.setItem(STORE,JSON.stringify(s))}
function mark(key){const s=state();s.done[key]=true;save(s)}
function nav(){const n=document.querySelector('.nav');if(!n)return;modules.forEach(([id,ic,t])=>{if(n.querySelector(`[data-view="${id}"]`))return;const b=document.createElement('button');b.className='nav-item';b.dataset.view=id;b.innerHTML=`<span>${ic}</span> ${H(t)}`;n.appendChild(b)})}
function dashboard(){const s=state(),done=Object.keys(s.done).length,pct=Math.min(100,Math.round((done/modules.length)*100)),avg=s.quizTotal?Math.round((s.quizCorrect/s.quizTotal)*100):0;app.innerHTML=`<div class="suite-hero"><span class="eyebrow red">RD INTRANET · TRAININGSZENTRUM</span><h1>Dein Rettungsdienst-Dashboard.</h1><p>ABCDE, Dokumentation, Medikamente, Eigenschutz, Psychiatrie, Ausbildung, Prüfungen, Wissen und Lernfortschritt in einer gemeinsamen Oberfläche.</p><div class="suite-toolbar"><div class="grow"><input id="suiteGlobalSearch" placeholder="Global suchen: ABCDE, Suizid, Medikament, Dokumentation …"></div><button class="suite-btn primary" data-suite-route="suche">🔎 Suche öffnen</button></div></div><div class="suite-grid" style="margin-bottom:18px"><div class="suite-stat"><small>Ausbildungsfortschritt</small><strong>${pct}%</strong><div class="suite-progress"><span style="width:${pct}%"></span></div></div><div class="suite-stat"><small>Quiz-Trefferquote</small><strong>${avg}%</strong><small>${s.quizCorrect}/${s.quizTotal} Antworten</small></div><div class="suite-stat"><small>Dokumentationen</small><strong>${s.docs}</strong><small>Trainingsfälle abgeschlossen</small></div><div class="suite-stat"><small>Prüfungsbestwert</small><strong>${s.examBest}%</strong><small>Lokaler Lernstand</small></div></div><div class="suite-dashboard-actions">${modules.slice(0,9).map(m=>`<button class="suite-card" data-suite-route="${m[0]}"><div class="ico">${m[1]}</div><h3>${m[2]}</h3><p>${m[3]}</p></button>`).join('')}</div><section class="section"><div class="suite-grid two"><div class="suite-card"><div class="suite-panel-head"><h3>Dein Lernweg</h3><span class="suite-badge blue">${done}/${modules.length}</span></div><div class="suite-list">${modules.slice(0,8).map(m=>`<div class="suite-list-row"><span>${m[1]} ${m[2]}</span><span class="suite-badge ${s.done[m[0]]?'green':''}">${s.done[m[0]]?'ERLEDIGT':'OFFEN'}</span></div>`).join('')}</div></div><div class="suite-card"><div class="suite-panel-head"><h3>Schnellstart</h3></div><div class="suite-list"><button class="suite-btn blue" data-suite-route="abcde">🩺 ABCDE-Fall starten</button><button class="suite-btn warn" data-suite-route="gefahren">🦺 Eigenschutz-Fall starten</button><button class="suite-btn" data-suite-route="pruefung">🏆 Prüfung starten</button><button class="suite-btn" data-suite-route="dokumentation">📋 Dokumentation öffnen</button></div><div class="suite-note" style="margin-top:12px">Trainingsmodus: Inhalte sind für Ausbildung/RP und ersetzen keine örtlichen SOPs, ärztlichen Anordnungen oder verbindlichen Vorgaben.</div></div></div></section>`;bindSuiteInputs()}
function abcde(){let s=state(),i=Math.min(abcdeSteps.length-1,s.abcde||0),step=abcdeSteps[i];app.innerHTML=`<div class="suite-hero"><span class="eyebrow">ABCDE-TRAINING</span><h1>Schritt für Schritt untersuchen</h1><p>Wähle die Antwort, die die strukturierte Untersuchung am besten abbildet. Der Fortschritt wird lokal gespeichert.</p></div><div class="suite-abcde">${abcdeSteps.map((x,k)=>`<button class="${k===i?'active':''}" data-abcde-step="${k}"><b>${x[0].split(' ')[0]}</b><br><small>${x[1]}</small></button>`).join('')}</div><div class="suite-question"><span class="suite-badge red">${step[0]}</span><h2>${step[2]}</h2><div class="suite-muted">Trainingsfrage – lokale SOP/Lehrunterlage bleibt maßgeblich.</div><div style="margin-top:14px">${step[3].map((c,k)=>`<label class="suite-choice"><input type="radio" name="abcde" value="${k}"><span>${H(c)}</span></label>`).join('')}</div><div class="suite-toolbar"><button class="suite-btn primary" id="abcdeNext">Antwort speichern & weiter</button><button class="suite-btn" data-suite-route="ausbildung">Zum Ausbildungsmodus</button></div><div id="abcdeFeedback"></div></div>`}
function documentation(){const now=new Date(),date=now.toLocaleDateString('de-DE'),time=now.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});app.innerHTML=`<div class="suite-hero"><span class="eyebrow">EINSATZDOKUMENTATION</span><h1>Trainingsbericht</h1><p>Dokumentiere einen simulierten Einsatz strukturiert. Es werden keine realen Patientendaten benötigt.</p></div><form class="suite-form" id="docForm"><div class="suite-card"><div class="suite-form row"><input name="einsatz" placeholder="Einsatznummer / Fallname" value="Training-${Date.now().toString().slice(-5)}"><input name="zeit" value="${H(date+' '+time)}"></div></div><div class="suite-card"><div class="suite-form row"><input name="ort" placeholder="Einsatzort"><input name="meldung" placeholder="Meldebild"></div><textarea name="anamnese" rows="4" placeholder="Anamnese / Fremdanamnese"></textarea><textarea name="befunde" rows="4" placeholder="ABCDE, Vitalwerte, relevante Befunde"></textarea><textarea name="massnahmen" rows="4" placeholder="Maßnahmen / Verlauf"></textarea><textarea name="uebergabe" rows="4" placeholder="Übergabe / Transport / Abschluss"></textarea></div><button class="suite-btn primary" type="submit">📋 Dokumentation abschließen</button></form><div id="docResult"></div>`}
function medlernen(){const meds=(window.RD_MEDS||[]),s=state(),idx=(s.medIndex||0)%Math.max(1,meds.length),m=meds[idx]||['Beispiel','Training','Kein Datensatz vorhanden','ampoule'];app.innerHTML=`<div class="suite-hero"><span class="eyebrow">MEDIKAMENTEN-LERNSYSTEM</span><h1>Karteikarte & Mini-Quiz</h1><p>${meds.length} lokale Einträge. Die Lernansicht nutzt bewusst keine Dosierungsanweisungen.</p></div><div class="suite-grid two"><article class="suite-card"><span class="suite-badge blue">Karte ${idx+1}/${meds.length}</span><h2 style="margin:12px 0 6px">${H(m[0])}</h2><div class="suite-chip-row"><span class="suite-chip">${H(m[1])}</span><span class="suite-chip">${H(m[3]||'Präparat')}</span></div><p>${H(m[2])}</p><div class="suite-note">Lernziel: Wirkstoff-/Produktname, Kategorie und Zweck kennen. Für reale Anwendung gelten ausschließlich eure geprüften lokalen SOP-/Medikamentenunterlagen.</div><button class="suite-btn primary" id="medNext">Nächste Karte →</button></article><article class="suite-card"><h3>Quiz</h3><p>Welche Kategorie gehört zur aktuellen Karte?</p><div>${[m[1], 'ABCDE','Diagnostik'].map((x,k)=>`<label class="suite-choice"><input type="radio" name="medquiz" value="${k}"><span>${H(x)}</span></label>`).join('')}</div><button class="suite-btn green" id="medCheck">Antwort prüfen</button><div id="medFeedback"></div></article></div>`}
function gefahren(){let n=state(),idx=n.hazardIndex||0,c=hazardCases[idx%hazardCases.length];app.innerHTML=`<div class="suite-hero suite-danger"><span class="eyebrow red">GEFAHREN & EIGENSCHUTZ</span><h1>${H(c.title)}</h1><p>Trainiere das Erkennen und Priorisieren von Gefahren vor der Patientenversorgung.</p></div><div class="suite-grid two"><div class="suite-card"><h3>Gefahrenlage</h3><div class="suite-chip-row">${c.hazards.map(x=>`<span class="suite-chip">⚠ ${H(x)}</span>`).join('')}</div><p style="margin-top:14px">Was ist vor dem nächsten Patientenkontakt zu berücksichtigen?</p><textarea id="hazardAnswer" rows="6" placeholder="Deine Lageeinschätzung …"></textarea><button class="suite-btn warn" id="hazardReveal">Bewertung anzeigen</button><div id="hazardFeedback"></div></div><div class="suite-card"><h3>Eigenschutz-Merkpunkte</h3><div class="suite-list"><div class="suite-list-row">👀 Lage beobachten <span class="suite-badge">Pflicht</span></div><div class="suite-list-row">🚪 Rückzugsweg <span class="suite-badge">Prüfen</span></div><div class="suite-list-row">🦺 Geeignete PSA <span class="suite-badge">Prüfen</span></div><div class="suite-list-row">📞 Unterstützung nachfordern <span class="suite-badge">Lageabhängig</span></div><div class="suite-list-row">⛔ Unsicheren Bereich nicht betreten <span class="suite-badge red">Wichtig</span></div></div><button class="suite-btn blue" id="hazardNext">Nächste Lage</button></div></div>`}
function psychiatrie(){const n=state(),i=n.psychIndex||0,c=psychCases[i%psychCases.length];app.innerHTML=`<div class="suite-hero"><span class="eyebrow">PSYCHIATRISCHE EINSATZLAGEN</span><h1>${H(c.title)}</h1><p>Kommunikation und Eigenschutz trainieren. Die Fälle sind bewusst ohne starre Zwangs-/Therapieanweisungen aufgebaut.</p></div><div class="suite-grid two"><div class="suite-card"><h3>Lage</h3><span class="suite-badge ${c.risk==='Hoch'?'red':'amber'}">Risiko: ${H(c.risk)}</span><div class="suite-list" style="margin-top:12px">${c.facts.map(x=>`<div class="suite-list-row">${H(x)}</div>`).join('')}</div></div><div class="suite-card"><h3>Wie gehst du kommunikativ vor?</h3>${c.choices.map((x,k)=>`<label class="suite-choice"><input type="radio" name="psych" value="${k}"><span><b>${H(x[0])}</b><small style="display:block;color:var(--muted);margin-top:4px">${H(x[1])}</small></span></label>`).join('')}<button class="suite-btn primary" id="psychCheck">Antwort prüfen</button><div id="psychFeedback"></div></div></div>`}
function ausbildung(){const s=state(),done=Object.keys(s.done).length,pct=Math.round(done/modules.length*100);app.innerHTML=`<div class="suite-hero"><span class="eyebrow">AUSBILDUNGSMODUS</span><h1>Dein persönlicher Lernpfad</h1><p>Arbeite Module nacheinander durch und markiere sie als abgeschlossen. Alles bleibt lokal im Browser.</p><div class="suite-progress"><span style="width:${pct}%"></span></div><p style="margin-bottom:0"><b>${pct}%</b> abgeschlossen · ${done}/${modules.length} Module</p></div><div class="suite-grid">${modules.filter(m=>m[0]!=='suche'&&m[0]!=='statistik').map(m=>`<button class="suite-card" data-suite-route="${m[0]}"><div class="ico">${m[1]}</div><h3>${m[2]}</h3><p>${m[3]}</p><span class="suite-badge ${s.done[m[0]]?'green':''}">${s.done[m[0]]?'✓ abgeschlossen':'offen'}</span></button>`).join('')}</div>`}
function pruefung(){const qs=[['ABCDE','Welche Struktur hilft bei einer systematischen Ersteinschätzung?',['ABCDE','Nur Blutdruck','Nur EKG'],0],['Eigenschutz','Was hat vor Betreten einer unklar gefährlichen Lage Priorität?',['Schnellster Patientenkontakt','Lage/Gefahren und Eigenschutz','Dokumentation'],1],['Psychiatrie','Was unterstützt Deeskalation am ehesten?',['Ruhige, klare Kommunikation und Distanz','Mehrere Personen reden gleichzeitig','Konfrontation'],0],['Dokumentation','Was sollte eine Übergabe enthalten?',['Nur den Namen','Relevante Befunde, Verlauf und Maßnahmen','Nur die Uhrzeit'],1],['Wissen','Was ist bei dynamischen Trainingsfällen wichtig?',['Keine Re-Evaluation','Verlauf beobachten und neu bewerten','Nur einmal messen'],1]];let i=0,answers=[];function draw(){const q=qs[i];app.innerHTML=`<div class="suite-hero"><span class="eyebrow">PRÜFUNGSMODUS</span><h1>Mini-Prüfung</h1><p>Frage ${i+1} von ${qs.length}. Bestehen ist hier kein klinischer Befähigungsnachweis, sondern ein lokaler Lerntest.</p></div><div class="suite-question"><span class="suite-badge blue">${H(q[0])}</span><h2>${H(q[1])}</h2>${q[2].map((x,k)=>`<label class="suite-choice"><input type="radio" name="exam" value="${k}"><span>${H(x)}</span></label>`).join('')}<button class="suite-btn primary" id="examNext">Antwort übernehmen</button><div id="examFeedback"></div></div>`}draw();const old=window.__suiteExamHandler;window.__suiteExamHandler=()=>{const q=qs[i],v=document.querySelector('input[name="exam"]:checked');if(!v){document.getElementById('examFeedback').innerHTML='<div class="suite-note suite-danger">Bitte eine Antwort auswählen.</div>';return}const ok=Number(v.value)===q[3];answers.push(ok);const s=state();s.quizTotal++;if(ok)s.quizCorrect++;save(s);if(i<qs.length-1){i++;draw()}else{const score=Math.round(answers.filter(Boolean).length/answers.length*100),st=state();st.examBest=Math.max(st.examBest,score);st.done.pruefung=true;save(st);app.innerHTML=`<div class="suite-hero"><span class="eyebrow red">PRÜFUNG ABGESCHLOSSEN</span><h1>${score}%</h1><p>${answers.filter(Boolean).length}/${answers.length} Fragen richtig.</p><button class="suite-btn primary" data-suite-route="statistik">📊 Statistik ansehen</button></div>`;}};document.getElementById('examNext').onclick=window.__suiteExamHandler}
function wissensdatenbank(){app.innerHTML=`<div class="suite-hero"><span class="eyebrow">WISSENSDATENBANK</span><h1>Rettungsdienst-Wissen durchsuchen</h1><p>${knowledge.length} verknüpfte Lernkarten als lokaler Startbestand. Neue Inhalte können später ergänzt werden.</p><div class="suite-toolbar"><div class="grow"><input id="knowledgeSearch" placeholder="Begriff oder Thema suchen …"></div><select id="knowledgeCat"><option value="">Alle Kategorien</option>${[...new Set(knowledge.map(x=>x[1]))].map(c=>`<option>${H(c)}</option>`).join('')}</select></div></div><div id="knowledgeResults" class="suite-search-results">${knowledge.map((x,i)=>`<article class="suite-search-item"><b>${H(x[0])}</b><span class="suite-badge blue" style="margin-left:7px">${H(x[1])}</span><small>${H(x[2])}</small></article>`).join('')}</div>`;bindKnowledge()}
function suche(){const all=[...knowledge.map(x=>({t:x[0],c:x[1],d:x[2],route:x[1]==='ABCDE'?'abcde':x[1]==='Psychiatrie'?'psychiatrie':x[1]==='Sicherheit'?'gefahren':'wissensdatenbank'})),...(window.RD_MEDS||[]).map(m=>({t:m[0],c:'Medikament',d:m[2],route:'medlernen'})),...(window.RD_DATA?.common||[]).map(x=>({t:x.title,c:x.cat,d:x.desc,route:'notfallbilder'}))];app.innerHTML=`<div class="suite-hero"><span class="eyebrow">GLOBALE INTELLIGENTE SUCHE</span><h1>Ein Suchfeld für das ganze Intranet</h1><p>Durchsucht Wissen, Medikamente und Einsatzsituationen gleichzeitig.</p><div class="suite-toolbar"><div class="grow"><input id="globalSearchFull" autofocus placeholder="z. B. Atemnot, Schlaganfall, Eigenschutz …"></div></div></div><div id="globalResults" class="suite-search-results"></div>`;const input=$('#globalSearchFull'),out=$('#globalResults');const go=()=>{const q=input.value.trim().toLowerCase();const r=q?all.filter(x=>(x.t+' '+x.c+' '+x.d).toLowerCase().includes(q)).slice(0,60):all.slice(0,20);out.innerHTML=r.length?r.map((x,i)=>`<button class="suite-search-item" data-suite-route="${x.route}"><b>${H(x.t)}</b><span class="suite-badge blue" style="margin-left:7px">${H(x.c)}</span><small>${H(x.d)}</small></button>`).join(''):'<div class="suite-note">Keine Treffer.</div>'};input.addEventListener('input',go);go()}
function statistik(){const s=state(),avg=s.quizTotal?Math.round(s.quizCorrect/s.quizTotal*100):0,pct=Math.round(Object.keys(s.done).length/modules.length*100);app.innerHTML=`<div class="suite-hero"><span class="eyebrow">STATISTIK & LERNFORTSCHRITT</span><h1>Dein Lernstand</h1><p>Alle Kennzahlen stammen aus lokal gespeicherten Trainingsaktionen dieses Browsers.</p></div><div class="suite-grid"><div class="suite-stat"><small>Module</small><strong>${Object.keys(s.done).length}/${modules.length}</strong></div><div class="suite-stat"><small>Fortschritt</small><strong>${pct}%</strong><div class="suite-progress"><span style="width:${pct}%"></span></div></div><div class="suite-stat"><small>Quiz-Trefferquote</small><strong>${avg}%</strong></div><div class="suite-stat"><small>Prüfungsbestwert</small><strong>${s.examBest}%</strong></div></div><section class="section"><div class="suite-card"><h3>Aktivitäten</h3><table class="suite-table"><tr><th>Bereich</th><th>Status</th></tr>${modules.map(m=>`<tr><td>${m[1]} ${m[2]}</td><td>${s.done[m[0]]?'✓ abgeschlossen':'offen'}</td></tr>`).join('')}</table><div class="suite-toolbar"><button class="suite-btn" id="resetStats">Lernstand zurücksetzen</button></div></div></section>`;$('#resetStats').onclick=()=>{if(confirm('Lokalen Lernstand wirklich löschen?')){localStorage.removeItem(STORE);statistik()}}}
function renderView(v){if(v==='dashboard')return dashboard();if(v==='abcde')return abcde();if(v==='dokumentation')return documentation();if(v==='medlernen')return medlernen();if(v==='gefahren')return gefahren();if(v==='psychiatrie')return psychiatrie();if(v==='ausbildung')return ausbildung();if(v==='pruefung')return pruefung();if(v==='wissensdatenbank')return wissensdatenbank();if(v==='suche')return suche();if(v==='statistik')return statistik();}
function currentView(){return document.querySelector('.nav-item.active')?.dataset.view||'dashboard'}
function markCurrent(v){if(['abcde','dokumentation','medlernen','gefahren','psychiatrie','ausbildung','pruefung','wissensdatenbank','statistik'].includes(v))mark(v)}
function bindKnowledge(){const s=$('#knowledgeSearch'),c=$('#knowledgeCat'),out=$('#knowledgeResults');const draw=()=>{const q=(s.value||'').toLowerCase(),cat=c.value;out.innerHTML=knowledge.filter(x=>(!q||(x.join(' ').toLowerCase().includes(q)))&&(!cat||x[1]===cat)).map(x=>`<article class="suite-search-item"><b>${H(x[0])}</b><span class="suite-badge blue" style="margin-left:7px">${H(x[1])}</span><small>${H(x[2])}</small></article>`).join('')||'<div class="suite-note">Keine Treffer.</div>'};s.oninput=draw;c.onchange=draw}
function bindSuiteInputs(){const g=$('#suiteGlobalSearch');if(g){g.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();renderView('suche')}}}}
function globalActions(e){const route=e.target.closest('[data-suite-route]')?.dataset.suiteRoute;if(route){e.preventDefault();const b=document.querySelector(`[data-view="${route}"]`);if(b)b.click();else renderView(route);return}const abc=e.target.closest('[data-abcde-step]')?.dataset.abcdeStep;if(abc!=null){const s=state();s.abcde=Number(abc);save(s);renderView('abcde');return}if(e.target.id==='abcdeNext'){const v=$('input[name="abcde"]:checked'),fb=$('#abcdeFeedback');if(!v){fb.innerHTML='<div class="suite-note suite-danger">Bitte zuerst einen Befund auswählen.</div>';return}const s=state();s.abcde++;if(s.abcde>=abcdeSteps.length){s.abcde=0;s.done.abcde=true;save(s);fb.innerHTML='<div class="suite-note">ABCDE-Trainingsrunde abgeschlossen.</div>'}else{save(s);renderView('abcde')}return}if(e.target.id==='docForm'||e.target.closest('#docForm')){return}if(e.target.id==='medNext'){const s=state();s.medIndex=(s.medIndex||0)+1;save(s);renderView('medlernen');return}if(e.target.id==='medCheck'){const s=state(),meds=window.RD_MEDS||[],idx=(s.medIndex||0)%Math.max(1,meds.length),m=meds[idx],v=$('input[name="medquiz"]:checked'),fb=$('#medFeedback');if(!v){fb.innerHTML='<div class="suite-note suite-danger">Antwort auswählen.</div>';return}s.quizTotal++;if(Number(v.value)===0){s.quizCorrect++;fb.innerHTML='<div class="suite-note">✅ Richtig.</div>'}else fb.innerHTML='<div class="suite-note suite-danger">❌ Noch einmal anschauen: Kategorie ist „'+H(m[1])+'“.</div>';save(s);return}if(e.target.id==='hazardReveal'){const s=$('#hazardAnswer').value.trim(),fb=$('#hazardFeedback');fb.innerHTML=`<div class="suite-note" style="margin-top:12px"><b>Trainingsreferenz:</b><br>${H(hazardCases[(state().hazardIndex||0)%hazardCases.length].answer)}<br><br><span class="suite-muted">Deine Eingabe kann sinnvoll sein, entscheidend sind lokale Gefahren- und Einsatzkonzepte.</span></div>`;mark('gefahren');return}if(e.target.id==='hazardNext'){const s=state();s.hazardIndex=(s.hazardIndex||0)+1;save(s);renderView('gefahren');return}if(e.target.id==='psychCheck'){const v=$('input[name="psych"]:checked'),fb=$('#psychFeedback');if(!v){fb.innerHTML='<div class="suite-note suite-danger">Bitte Antwort auswählen.</div>';return}const c=psychCases[(state().psychIndex||0)%psychCases.length],ok=Number(v.value)===1|| (c.title.includes('Suizid')&&Number(v.value)===1);fb.innerHTML=`<div class="suite-note ${ok?'':'suite-danger'}" style="margin-top:12px">${ok?'✅ Deeskalations-/Sicherheitsorientierter Ansatz.':'⚠️ Trainingshinweis: Distanz, Ausweg, ruhige Kommunikation und Unterstützung sind häufig die sicherere Ausgangsbasis.'}</div>`;mark('psychiatrie');return}if(e.target.id==='docForm')return}
function docSubmit(e){if(e.target.id!=='docForm')return;e.preventDefault();const s=state();s.docs++;s.done.dokumentation=true;save(s);const fd=new FormData(e.target),rows=[['Fall',fd.get('einsatz')],['Zeit',fd.get('zeit')],['Ort',fd.get('ort')],['Meldung',fd.get('meldung')],['Anamnese',fd.get('anamnese')],['Befunde',fd.get('befunde')],['Maßnahmen',fd.get('massnahmen')],['Übergabe',fd.get('uebergabe')]];$('#docResult').innerHTML=`<div class="suite-doc" style="margin-top:16px"><div class="suite-panel-head"><h3>Dokumentation abgeschlossen</h3><button class="suite-btn" id="docPrint">Drucken</button></div><table class="suite-table">${rows.map(r=>`<tr><th>${H(r[0])}</th><td>${H(r[1]||'—')}</td></tr>`).join('')}</table></div>`;$('#docPrint').onclick=()=>window.print()}
const baseRender=window.render;
window.render=function(){const v=currentView();if(['dashboard','abcde','dokumentation','medlernen','gefahren','psychiatrie','ausbildung','pruefung','wissensdatenbank','suche','statistik'].includes(v)){renderView(v);if(v!=='dashboard'&&v!=='suche')markCurrent(v);return}baseRender()};
nav();
document.addEventListener('click',globalActions);
document.addEventListener('submit',docSubmit);
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();const b=document.querySelector('[data-view="suche"]');if(b)b.click()}});
setTimeout(()=>window.render(),0);
})();
