(()=>{
const app=document.getElementById('app');
const STORE='rd-suite-progress-v2';
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const CORE=[
 ['abcde','🩺','ABCDE-Training','Strukturierte Untersuchung mit Feedback'],
 ['dokumentation','📋','Einsatzdokumentation','Einen Trainingsfall vollständig dokumentieren'],
 ['medlernen','💊','Medikamenten-Lernen','Karteikarten und Wissensquiz'],
 ['gefahren','🦺','Gefahren & Eigenschutz','Gefahren erkennen und Entscheidungen trainieren'],
 ['psychiatrie','🧠','Psychiatrische Einsatzlagen','Kommunikation, Deeskalation und Eigenschutz'],
 ['pruefung','🏆','Prüfungsmodus','Abschlussprüfung mit Bestehensgrenze'],
 ['wissensdatenbank','📚','Wissensdatenbank','Lernkarten lesen und Wissen festigen']
];
const TOOLS=[
 ['ausbildung','🎓','Ausbildungsmodus','Gesamten Lernpfad verwalten'],
 ['suche','🔎','Globale Suche','Alle Lern- und Intranet-Inhalte durchsuchen'],
 ['statistik','📊','Statistik & Fortschritt','Lernstand, Ergebnisse und Aktivitäten']
];
const abcdeQuestions=[
 ['A – Airway','Welche Beobachtung gehört primär zu A?',['Atemweg und Schutzreflexe','Atemfrequenz','Blutdruck','Temperatur'],0],
 ['B – Breathing','Was gehört zu einer strukturierten B-Beurteilung?',['Atemarbeit und Atemfrequenz','Nur Puls','Nur Hautfarbe','Nur Gewicht'],0],
 ['C – Circulation','Welche Kombination unterstützt die Kreislaufbeurteilung?',['Puls, Blutdruck, Haut und Blutung','Nur Temperatur','Nur Pupillen','Nur Schmerz'],0],
 ['D – Disability','Was gehört zu D?',['Bewusstsein und neurologische Auffälligkeiten','Nur Körpergröße','Nur Temperatur','Nur Medikamentenname'],0],
 ['E – Exposure','Was ergänzt die Untersuchung sinnvoll?',['Verletzungen, Temperatur und Umfeld','Nur Blutdruck','Nur Puls','Nur SpO₂'],0]
];
const hazardCases=[
 {title:'Verkehrsunfall auf Landstraße',facts:['Fließender Verkehr','Instabiles Fahrzeug','Glassplitter'],q:'Was ist vor dem Patientenkontakt am wichtigsten?',a:['Sicheren Standbereich wählen, Verkehr/Gefahren berücksichtigen und Unterstützung nachfordern.','Direkt zur Fahrertür gehen, ohne die Lage zu sichern.','Zuerst die Dokumentation beginnen.'],c:0},
 {title:'Unbekannter Stoff im Keller',facts:['Unbekannter Stoff','Mögliche Dämpfe','Enger Zugang'],q:'Welche Reaktion passt am besten?',a:['Nicht ungeschützt vorgehen; Gefahrenbereich, PSA und zuständige Kräfte berücksichtigen.','Kurz hineingehen und den Stoff identifizieren.','Fenster schließen und Patient sofort herausholen.'],c:0},
 {title:'Stromunfall in Werkstatt',facts:['Elektrische Energie','Maschinen','Enge Umgebung'],q:'Was hat Priorität?',a:['Sichere Abschaltung/Annäherung nach lokalem Verfahren.','Patient sofort anfassen.','Nur Vitalwerte dokumentieren.'],c:0},
 {title:'Aggressive Person',facts:['Unklare Fremdgefährdung','Publikum','Unklare Bewaffnung'],q:'Welche Taktik ist sinnvoll?',a:['Abstand, Rückzugsweg und Unterstützung/Polizei nach Lage.','Dicht herantreten und laut argumentieren.','Alle Teammitglieder gleichzeitig sprechen lassen.'],c:0},
 {title:'Wohnungsbrand',facts:['Rauch','Hitze','Unübersichtlicher Innenraum'],q:'Was steht im Vordergrund?',a:['Eigenschutz und sichere Zusammenarbeit mit der Feuerwehr.','Ungesichert in den Brandbereich gehen.','Nur die Personalien erheben.'],c:0},
 {title:'Gefahrgut-Transport',facts:['Beschädigtes Fahrzeug','Unklare Kennzeichnung','Mögliche Kontamination'],q:'Was ist vor der Annäherung wichtig?',a:['Gefahr erkennen, Abstand halten und geeignete Kräfte/Informationen organisieren.','Container öffnen.','Unmittelbar in den Nahbereich gehen.'],c:0}
];
const psychCases=[
 {title:'Akute Unruhe im Wohnraum',risk:'Mittel',facts:['Patient laut und angespannt','Angehörige vor Ort','Rückzugsweg beachten'],q:'Welcher Ansatz ist am ehesten deeskalierend?',a:['Abstand, ruhige Ansprache, klarer Ausweg und Unterstützung.','Konfrontativ beweisen, dass der Patient falsch liegt.','Mehrere Personen gleichzeitig sprechen lassen.'],c:0},
 {title:'Paranoide Wahrnehmung',risk:'Hoch',facts:['Patient fühlt sich verfolgt','Spricht schnell','Keine sichtbare Waffe'],q:'Was ist sinnvoll?',a:['Ruhig bleiben, Abstand halten und nicht konfrontativ argumentieren.','Die Wahrnehmung lächerlich machen.','Ohne Erklärung körperlich näher kommen.'],c:0},
 {title:'Suizidale Krise',risk:'Hoch',facts:['Konkrete Suizidgedanken','Gefährliche Gegenstände möglich','Angehörige vor Ort'],q:'Was ist zu priorisieren?',a:['Lage/Eigenschutz sichern, Unterstützung nachfordern und lokalem Krisenablauf folgen.','Risiko ignorieren und nur dokumentieren.','Patient allein lassen.'],c:0},
 {title:'Intoxikation mit Verhaltensauffälligkeit',risk:'Hoch',facts:['Unklare Substanz','Verändertes Verhalten','Umfeld unübersichtlich'],q:'Was gehört zur sicheren Ausgangslage?',a:['Abstand, Umfeld, Bewusstsein/Vitalfunktionen und Unterstützung berücksichtigen.','Nur die Substanz erraten.','Nur die Angehörigen befragen und Patient unbeobachtet lassen.'],c:0},
 {title:'Angst-/Panikreaktion',risk:'Mittel',facts:['Starke Angst','Schnelle Atmung','Ansprechbar'],q:'Wie kommunizieren?',a:['Ruhig, klar, respektvoll und strukturiert.','Drohungen einsetzen.','Patient ignorieren.'],c:0}
];
const examBank=[
 ['ABCDE','Welche Struktur unterstützt eine systematische Ersteinschätzung?',['ABCDE','Nur Blutdruck','Nur EKG','Nur Temperatur'],0],
 ['Eigenschutz','Was ist bei unklarer Gefahr wichtig?',['Lage/Gefahren und Eigenschutz','Sofort hineingehen','Nur dokumentieren','Nur Patientendaten erfassen'],0],
 ['Psychiatrie','Was unterstützt Deeskalation?',['Ruhige Kommunikation und Distanz','Konfrontation','Mehrere Stimmen gleichzeitig','Provokation'],0],
 ['Dokumentation','Was gehört in eine nachvollziehbare Dokumentation?',['Befunde, Zeiten, Maßnahmen und Verlauf','Nur Name','Nur Uhrzeit','Nur Diagnose'],0],
 ['Re-Evaluation','Was ist bei Veränderungen wichtig?',['Erneut strukturiert beurteilen','Nur einmal messen','Dokumentation beenden','Patient nicht mehr beobachten'],0],
 ['Anamnese','Welche Angabe ist besonders hilfreich?',['Beginn und Verlauf der Beschwerden','Nur Körpergröße','Nur Beruf','Nur Wohnort'],0],
 ['Übergabe','Was ist bei einer strukturierten Übergabe wichtig?',['Relevante Befunde, Verlauf und Maßnahmen','Nur Fahrzeugnummer','Nur Name','Nur Gewicht'],0],
 ['Hygiene','Was gehört grundsätzlich zur sicheren Versorgung?',['Situationsgerechte Hygiene und PSA','Keine Vorbereitung','Nur Handschuhe unabhängig von der Lage','Nur Desinfektion des Fahrzeugs'],0],
 ['MANV','Was gehört zu einem MANV-Konzept?',['Sichtung, Führung und Ressourcenstruktur','Nur Einzelpatientenversorgung','Nur Dokumentation','Nur Transport'],0],
 ['Ausbildung','Wofür dient der Lernfortschritt?',['Gezieltes Wiederholen und Nachverfolgen des Lernstands','Nur Statistik ohne Lernziel','Nur Dekoration','Nur Prüfungsergebnisse'] ,0]
];
const knowledge=[
 ['ABCDE','ABCDE','Strukturierte Ersteinschätzung von A bis E.'],['Airway','ABCDE','A fokussiert auf Atemweg, Schutzreflexe und sichtbare Obstruktion.'],['Breathing','ABCDE','B umfasst Atemarbeit, Atemfrequenz, Oxygenierung und klinische Atemzeichen.'],['Circulation','ABCDE','C umfasst Puls, Blutdruck, Hautzeichen, Blutungen und Perfusion.'],['Disability','ABCDE','D umfasst Bewusstsein und neurologische Auffälligkeiten.'],['Exposure','ABCDE','E betrachtet Gesamtzustand, Verletzungen, Temperatur und Umfeld.'],['Eigenschutz','Sicherheit','Vor Patientenkontakt Lage, Gefahren, Rückzugsweg, PSA und Unterstützung prüfen.'],['Verkehrsunfall','Sicherheit','Verkehr, Fahrzeugstabilität und weitere Gefahren in die Lageeinschätzung einbeziehen.'],['Gasgeruch','Sicherheit','Gefahrenbereich beachten und nicht ungeschützt betreten; lokale Abläufe sind maßgeblich.'],['Aggressive Person','Psychiatrie','Abstand, Ausweg, ruhige Kommunikation und Unterstützung beachten.'],['Akute Psychose','Psychiatrie','Reizarm, respektvoll und klar kommunizieren; nicht konfrontativ argumentieren.'],['Suizidale Krise','Psychiatrie','Eigengefährdung ernst nehmen, Lage sichern und lokalen Krisenablauf anwenden.'],['Intoxikation','Psychiatrie','Substanz, Zeitpunkt, Verlauf und Begleitstoffe systematisch erheben.'],['Dokumentation','Dokumentation','Zeitpunkte, Beschwerden, Befunde, Maßnahmen und Verlauf nachvollziehbar festhalten.'],['Übergabe','Dokumentation','Problem, relevante Befunde, Verlauf und erfolgte Maßnahmen strukturiert weitergeben.'],['Vitalwerte','Diagnostik','Vitalwerte sind Momentaufnahmen und sollten im Verlauf erneut bewertet werden.'],['Bewusstsein','Diagnostik','Bewusstseinslage beobachten und Veränderungen zeitnah dokumentieren.'],['Schmerz','Diagnostik','Schmerz standardisiert erfassen und im Verlauf erneut bewerten.'],['Anaphylaxie','Notfallbild','Akute allergische Reaktion kann Atemweg, Atmung und Kreislauf betreffen; lokale SOP beachten.'],['Thoraxschmerz','Notfallbild','Beginn, Charakter, Begleitsymptome und Verlauf strukturiert erfassen.'],['Dyspnoe','Notfallbild','Atemnot nach Schwere, Beginn, Auslösern und Begleitzeichen beurteilen.'],['Schlaganfall','Notfallbild','Neurologische Ausfälle und Zeitpunkt/letzte sichere Normalität dokumentieren.'],['Hypoglykämie','Notfallbild','Bewusstseinsveränderung und Glukosewert gemeinsam betrachten; lokale Abläufe anwenden.'],['MANV','Einsatzführung','Sichtung, Führung, Kommunikation und Ressourcen nach lokalem Konzept strukturieren.'],['Hygiene','Sicherheit','Handhygiene, PSA und situationsgerechte Kontaminationsvermeidung gehören zum sicheren Arbeiten.'],['Prüfungsvorbereitung','Ausbildung','Fälle bearbeiten, Fehler analysieren und schwache Themen gezielt wiederholen.']
];
const defaults={completed:{},attempts:{},abcdeIndex:0,medIndex:0,medSeen:[],medQuiz:0,hazardIndex:0,hazardAnswered:0,hazardCorrect:0,psychIndex:0,psychAnswered:0,psychCorrect:0,knowledgeRead:[],quizCorrect:0,quizTotal:0,examBest:0,examAttempts:0,docs:0,updatedAt:Date.now()};
function state(){let raw={};try{raw=JSON.parse(localStorage.getItem(STORE)||'{}')}catch{};const s=Object.assign({},defaults,raw);s.completed=Object.assign({},defaults.completed,raw.completed||raw.done||{});s.attempts=Object.assign({},defaults.attempts,raw.attempts||{});s.medSeen=Array.isArray(raw.medSeen)?raw.medSeen:[];s.knowledgeRead=Array.isArray(raw.knowledgeRead)?raw.knowledgeRead:[];return s}
function save(s){s.updatedAt=Date.now();localStorage.setItem(STORE,JSON.stringify(s))}
function complete(id){const s=state();s.completed[id]=true;save(s)}
function progress(){const s=state(),done=CORE.filter(m=>s.completed[m[0]]).length;return {done,total:CORE.length,pct:Math.round(done/CORE.length*100)}}
function label(id){return [...CORE,...TOOLS].find(x=>x[0]===id)?.[2]||'Lernbereich'}
function button(id,kind='suite-btn'){return `<button class="${kind}" data-suite-route="${id}">${esc(label(id))}</button>`}
function dashboard(){const s=state(),p=progress(),avg=s.quizTotal?Math.round(s.quizCorrect/s.quizTotal*100):0;app.innerHTML=`<div class="suite-hero learn-hero"><span class="eyebrow red">RD INTRANET · LERNZENTRUM</span><h1>Startseite – dein Lernzentrum.</h1><p>Alle Ausbildungsinhalte, Prüfungen und Lernfortschritte an einem Ort. Der Fortschritt wird ausschließlich aus tatsächlich abgeschlossenen Lernleistungen berechnet.</p><div class="learn-hero-row"><div class="learn-hero-progress"><div class="learn-progress-meta"><span>Gesamtfortschritt</span><strong>${p.pct}%</strong></div><div class="suite-progress"><span style="width:${p.pct}%"></span></div><small>${p.done} von ${p.total} Lernmodulen abgeschlossen</small></div><button class="suite-btn primary" data-suite-route="ausbildung">🎓 Lernpfad öffnen</button></div></div><section class="suite-grid learn-stats"><div class="suite-stat"><small>Lernmodule</small><strong>${p.done}/${p.total}</strong><span>abgeschlossen</span></div><div class="suite-stat"><small>Quiz-Trefferquote</small><strong>${avg}%</strong><span>${s.quizCorrect}/${s.quizTotal} Antworten</span></div><div class="suite-stat"><small>Prüfungsbestwert</small><strong>${s.examBest}%</strong><span>${s.examAttempts} Versuch(e)</span></div><div class="suite-stat"><small>Dokumentationen</small><strong>${s.docs}</strong><span>Trainingsberichte</span></div></section><section class="learn-section"><div class="learn-section-head"><div><span class="eyebrow">LERNMODULE</span><h2>Dein Lernpfad</h2><p>Jedes Modul hat eine echte Abschlussbedingung.</p></div><button class="suite-btn" data-suite-route="statistik">📊 Statistik</button></div><div class="learn-module-grid">${CORE.map(m=>{const ok=s.completed[m[0]];return `<button class="learn-module ${ok?'done':''}" data-suite-route="${m[0]}"><span class="learn-module-icon">${m[1]}</span><div><div class="learn-module-title">${m[2]} ${ok?'<span class="suite-badge green">ERLEDIGT</span>':'<span class="suite-badge">OFFEN</span>'}</div><p>${m[3]}</p></div><span class="learn-arrow">›</span></button>`}).join('')}</div></section><section class="learn-section"><div class="learn-section-head"><div><span class="eyebrow">WERKZEUGE</span><h2>Weitere Bereiche</h2><p>Diese Bereiche unterstützen das Lernen und zählen nicht als zusätzliche Prozentpunkte.</p></div></div><div class="learn-tools-grid">${TOOLS.map(m=>`<button class="learn-tool" data-suite-route="${m[0]}"><span>${m[1]}</span><div><b>${m[2]}</b><small>${m[3]}</small></div></button>`).join('')}</div></section>`}
function shell(title,eyebrow,desc,body){app.innerHTML=`<div class="suite-hero"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${desc}</p></div>${body}`}
function abcde(){const s=state(),i=Math.min(abcdeQuestions.length-1,Math.max(0,s.abcdeIndex||0)),q=abcdeQuestions[i];shell('ABCDE-Training','ABCDE · INTERAKTIV','Beantworte jeden Schritt. Erst nach dem vollständigen Durchlauf wird das Modul als abgeschlossen gespeichert.',`<div class="suite-card learning-card"><div class="learn-question-top"><span class="suite-badge red">Schritt ${i+1}/${abcdeQuestions.length}</span><span class="suite-badge blue">${q[0]}</span></div><h2>${esc(q[1])}</h2><div class="suite-choice-list">${q[2].map((x,k)=>`<label class="suite-choice"><input type="radio" name="abcde-answer" value="${k}"><span>${esc(x)}</span></label>`).join('')}</div><div id="abcdeFeedback"></div><div class="suite-toolbar"><button class="suite-btn primary" data-action="abcde-check">Antwort prüfen</button>${i>0?'<button class="suite-btn" data-action="abcde-reset">Neu starten</button>':''}</div></div>`)}
function documentation(){const now=new Date();shell('Einsatzdokumentation','DOKUMENTATION · TRAINING','Ein vollständiger Trainingsbericht. Pflichtfelder müssen ausgefüllt werden, bevor das Modul abgeschlossen wird.',`<form id="docForm" class="suite-form learning-card"><div class="suite-form-row"><label>Einsatz/Fall<input name="fall" required value="Training-${Date.now().toString().slice(-5)}"></label><label>Zeit<input name="zeit" required value="${esc(now.toLocaleString('de-DE'))}"></label></div><div class="suite-form-row"><label>Ort<input name="ort" required placeholder="z. B. Wohnung / Straße"></label><label>Meldebild<input name="meldung" required placeholder="z. B. Dyspnoe"></label></div><label>Anamnese / Fremdanamnese<textarea name="anamnese" rows="4" required></textarea></label><label>ABCDE / Vitalwerte / Befunde<textarea name="befunde" rows="5" required></textarea></label><label>Maßnahmen / Verlauf<textarea name="massnahmen" rows="5" required></textarea></label><label>Übergabe / Transport / Abschluss<textarea name="uebergabe" rows="4" required></textarea></label><div class="suite-note">Trainingsdokumentation ohne reale Patientendaten. Für produktiven Einsatz nur geprüfte lokale Dokumentationsvorgaben verwenden.</div><button class="suite-btn primary" type="submit">📋 Bericht abschließen</button></form><div id="docResult"></div>`)}
function medlernen(){const meds=window.RD_MEDS||[],s=state();if(!meds.length){shell('Medikamenten-Lernen','MEDIKAMENTE · LERNEN','Keine Medikamentendaten geladen.','<div class="suite-note suite-danger">RD_MEDS ist leer oder nicht geladen.</div>');return}const idx=(s.medIndex||0)%meds.length,m=meds[idx],cat=m[1]||'Kategorie',options=[cat,'Diagnostik','ABCDE'].map((x,j)=>j===0?x:['Diagnostik','Sicherheit'][j-1]||'Kategorie');shell('Medikamenten-Lernen','MEDIKAMENTE · KARTEIKARTEN',`${s.medSeen.length} von mindestens 5 Karten gesehen. Nach fünf Karten und fünf Quizantworten wird das Modul abgeschlossen.`,`<div class="suite-grid two"><article class="suite-card learning-card"><div class="learn-question-top"><span class="suite-badge blue">Karte ${idx+1}/${meds.length}</span><span class="suite-badge">${esc(cat)}</span></div><h2>${esc(m[0])}</h2><p class="learn-card-copy">${esc(m[2]||'Kein Beschreibungstext vorhanden.')}</p><div class="suite-note">Lernfokus: Name, Kategorie und Zweck verstehen. Keine Dosierungs- oder Applikationsanweisung.</div><button class="suite-btn primary" data-action="med-next">Karte als gelernt markieren →</button></article><article class="suite-card learning-card"><h3>Mini-Quiz</h3><p>Welche Kategorie gehört zur aktuellen Karte?</p>${[cat,'Diagnostik','Sicherheit'].map((x,k)=>`<label class="suite-choice"><input type="radio" name="med-answer" value="${k}"><span>${esc(x)}</span></label>`).join('')}<div id="medFeedback"></div><button class="suite-btn green" data-action="med-check">Antwort prüfen</button><small class="learn-progress-note">Quizantworten: ${Math.min(5,s.medQuiz)}/5 · Gesehene Karten: ${Math.min(5,s.medSeen.length)}/5</small></article></div>`)}
function gefahren(){const s=state(),i=(s.hazardIndex||0)%hazardCases.length,c=hazardCases[i];shell('Gefahren & Eigenschutz','SICHERHEIT · FALLTRAINING',`Fall ${i+1}/${hazardCases.length}. Beantworte alle sechs Fälle; ab 60% wird das Modul abgeschlossen.`, `<div class="suite-grid two"><div class="suite-card learning-card"><span class="suite-badge red">Lage</span><h2>${esc(c.title)}</h2><div class="suite-chip-row">${c.facts.map(x=>`<span class="suite-chip">⚠ ${esc(x)}</span>`).join('')}</div><h3>${esc(c.q)}</h3>${c.a.map((x,k)=>`<label class="suite-choice"><input type="radio" name="hazard-answer" value="${k}"><span>${esc(x)}</span></label>`).join('')}<div id="hazardFeedback"></div><button class="suite-btn warn" data-action="hazard-check">Antwort prüfen</button></div><div class="suite-card"><div class="suite-panel-head"><h3>Fortschritt</h3><span class="suite-badge blue">${s.hazardAnswered}/6</span></div><div class="suite-list"><div class="suite-list-row"><span>Fälle beantwortet</span><b>${s.hazardAnswered}/6</b></div><div class="suite-list-row"><span>Richtig</span><b>${s.hazardCorrect}</b></div><div class="suite-list-row"><span>Abschluss</span><b>${s.completed.gefahren?'✅ Erledigt':'≥ 60 %'}</b></div></div><button class="suite-btn" data-action="hazard-reset">Training zurücksetzen</button></div></div>`)}
function psychiatrie(){const s=state(),i=(s.psychIndex||0)%psychCases.length,c=psychCases[i];shell('Psychiatrische Einsatzlagen','PSYCHIATRIE · FALLTRAINING',`Fall ${i+1}/${psychCases.length}. Alle fünf Fälle werden einmal beantwortet und anschließend ausgewertet.`, `<div class="suite-grid two"><div class="suite-card learning-card"><div class="learn-question-top"><span class="suite-badge ${c.risk==='Hoch'?'red':'amber'}">Risiko: ${esc(c.risk)}</span></div><h2>${esc(c.title)}</h2><div class="suite-list">${c.facts.map(x=>`<div class="suite-list-row">${esc(x)}</div>`).join('')}</div></div><div class="suite-card learning-card"><h3>${esc(c.q)}</h3>${c.a.map((x,k)=>`<label class="suite-choice"><input type="radio" name="psych-answer" value="${k}"><span>${esc(x)}</span></label>`).join('')}<div id="psychFeedback"></div><button class="suite-btn primary" data-action="psych-check">Antwort prüfen</button></div></div>`)}
function ausbildung(){const p=progress(),s=state();shell('Ausbildungsmodus','LERNPFAD · ÜBERSICHT','Hier siehst du nur die echten Lernmodule. Werkzeuge wie Suche und Statistik zählen nicht als Lernmodule.',`<div class="suite-card learning-card"><div class="learn-progress-meta"><span>Gesamtfortschritt</span><strong>${p.pct}%</strong></div><div class="suite-progress"><span style="width:${p.pct}%"></span></div><p>${p.done}/${p.total} Lernmodule abgeschlossen</p></div><div class="learn-module-list">${CORE.map(m=>`<button class="learn-module ${s.completed[m[0]]?'done':''}" data-suite-route="${m[0]}"><span class="learn-module-icon">${m[1]}</span><div><b>${m[2]}</b><small>${m[3]}</small></div><span>${s.completed[m[0]]?'✅':'→'}</span></button>`).join('')}</div>`)}
function pruefung(){let questions=[...examBank].sort(()=>Math.random()-.5),i=0,answers=[];function draw(){const q=questions[i];shell('Prüfungsmodus','ABSCHLUSSPRÜFUNG',`Frage ${i+1}/${questions.length}. Bestehen ab 70%. Ein bestandener Versuch schließt das Prüfungsmodul ab.`,`<div class="suite-card learning-card"><div class="learn-question-top"><span class="suite-badge blue">${esc(q[0])}</span><span class="suite-badge">${i+1}/${questions.length}</span></div><h2>${esc(q[1])}</h2>${q[2].map((x,k)=>`<label class="suite-choice"><input type="radio" name="exam-answer" value="${k}"><span>${esc(x)}</span></label>`).join('')}<div id="examFeedback"></div><button class="suite-btn primary" data-action="exam-next">Antwort übernehmen</button></div>`)}draw();window.__examSession={questions,answers,getIndex:()=>i,next:()=>{const q=questions[i],v=document.querySelector('input[name="exam-answer"]:checked'),fb=document.getElementById('examFeedback');if(!v){fb.innerHTML='<div class="suite-note suite-danger">Bitte eine Antwort auswählen.</div>';return}const ok=Number(v.value)===q[3];answers.push(ok);const s=state();s.quizTotal++;if(ok)s.quizCorrect++;save(s);if(i<questions.length-1){i++;draw()}else{const score=Math.round(answers.filter(Boolean).length/questions.length*100),st=state();st.examAttempts++;st.examBest=Math.max(st.examBest,score);if(score>=70)st.completed.pruefung=true;save(st);shell(score>=70?'Prüfung bestanden':'Prüfung noch nicht bestanden',score>=70?'PRÜFUNG · BESTANDEN':'PRÜFUNG · WIEDERHOLEN',`${answers.filter(Boolean).length}/${questions.length} richtig · ${score}%`,`<div class="suite-card learning-card"><div class="suite-kv"><div><small>Ergebnis</small><b>${score}%</b></div><div><small>Grenze</small><b>70%</b></div><div><small>Status</small><b>${score>=70?'✅ BESTANDEN':'↻ WIEDERHOLEN'}</b></div></div><div class="suite-toolbar"><button class="suite-btn primary" data-suite-route="pruefung">Neue Prüfung</button><button class="suite-btn" data-suite-route="statistik">Statistik öffnen</button></div></div>`);}}}
function wissensdatenbank(){const s=state(),read=new Set(s.knowledgeRead);shell('Wissensdatenbank','WISSEN · LERNKARTEN',`${read.size} von mindestens 10 Lernkarten gelesen. Klicke bei einer Karte auf „Als gelernt markieren“.`,`<div class="suite-toolbar"><div class="grow"><input id="knowledgeSearch" placeholder="Begriff oder Thema suchen …"></div><select id="knowledgeCat"><option value="">Alle Kategorien</option>${[...new Set(knowledge.map(x=>x[1]))].map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div id="knowledgeResults" class="learn-knowledge-grid"></div>`);renderKnowledge()}
function renderKnowledge(){const out=document.getElementById('knowledgeResults');if(!out)return;const s=state(),q=(document.getElementById('knowledgeSearch')?.value||'').toLowerCase(),cat=document.getElementById('knowledgeCat')?.value||'';out.innerHTML=knowledge.filter((x,i)=>(!q||x.join(' ').toLowerCase().includes(q))&&(!cat||x[1]===cat)).map((x,i)=>`<article class="learn-knowledge-card"><div><span class="suite-badge blue">${esc(x[1])}</span><h3>${esc(x[0])}</h3><p>${esc(x[2])}</p></div><button class="suite-btn ${s.knowledgeRead.includes(i)?'green':''}" data-action="knowledge-read" data-index="${i}">${s.knowledgeRead.includes(i)?'✓ Gelernt':'Als gelernt markieren'}</button></article>`).join('')||'<div class="suite-note">Keine Treffer.</div>'}
function suche(){const meds=(window.RD_MEDS||[]).map((m,i)=>({t:m[0],c:'Medikament',d:m[2]||'',r:'medlernen',i}));const cases=(window.RD_DATA?.common||[]).map(x=>({t:x.title,c:x.cat||'Notfallbild',d:x.desc||'',r:'notfallbilder'}));const know=knowledge.map((x,i)=>({t:x[0],c:x[1],d:x[2],r:'wissensdatenbank',i}));const all=[...know,...meds,...cases];shell('Globale Suche','SUCHEN · ALLES FINDEN','Direktsuche über Wissen, Medikamente und Notfallbilder. Treffer erscheinen sofort beim Tippen.',`<div class="suite-card search-card"><input id="globalSearchFull" class="learn-search-input" autofocus placeholder="z. B. Atemnot, Eigenschutz, Aspirin …"><small id="searchCount"></small></div><div id="globalResults" class="suite-search-results"></div>`);const go=()=>{const q=(document.getElementById('globalSearchFull').value||'').trim().toLowerCase();const r=q?all.filter(x=>(x.t+' '+x.c+' '+x.d).toLowerCase().includes(q)).slice(0,80):[];document.getElementById('searchCount').textContent=q?`${r.length} Treffer`:'Bitte Suchbegriff eingeben';document.getElementById('globalResults').innerHTML=r.length?r.map(x=>`<button class="suite-search-item" data-suite-route="${x.r}"><b>${esc(x.t)}</b><span class="suite-badge blue">${esc(x.c)}</span><small>${esc(x.d)}</small></button>`).join(''):'<div class="suite-note">${q?'Keine Treffer.':'Noch keine Suche gestartet.'}</div>'};document.getElementById('globalSearchFull').addEventListener('input',go);go()}
function statistik(){const s=state(),p=progress(),avg=s.quizTotal?Math.round(s.quizCorrect/s.quizTotal*100):0;app.innerHTML=`<div class="suite-hero"><span class="eyebrow">STATISTIK · LERNFORTSCHRITT</span><h1>Dein Lernstand</h1><p>Prozentwerte basieren nur auf den sieben echten Lernmodulen.</p></div><div class="suite-grid learn-stats"><div class="suite-stat"><small>Gesamt</small><strong>${p.pct}%</strong><span>${p.done}/${p.total} Module</span></div><div class="suite-stat"><small>Quiz</small><strong>${avg}%</strong><span>${s.quizCorrect}/${s.quizTotal}</span></div><div class="suite-stat"><small>Prüfung</small><strong>${s.examBest}%</strong><span>${s.examAttempts} Versuche</span></div><div class="suite-stat"><small>Dokumentation</small><strong>${s.docs}</strong><span>Berichte</span></div></div><div class="suite-card learning-card"><div class="suite-panel-head"><h3>Modulstatus</h3><span class="suite-badge blue">${p.done}/${p.total}</span></div><div class="learn-status-table">${CORE.map(m=>`<div><span>${m[1]} ${m[2]}</span><b class="${s.completed[m[0]]?'ok':''}">${s.completed[m[0]]?'ERLEDIGT':'OFFEN'}</b></div>`).join('')}</div><div class="suite-toolbar"><button class="suite-btn" data-action="reset-learning">Lernstand zurücksetzen</button><button class="suite-btn" data-suite-route="ausbildung">Lernpfad öffnen</button></div></div>`}
function renderView(v){({dashboard,abcde,documentation,medlernen,gefahren,psychiatrie,ausbildung,pruefung,wissensdatenbank,suche,statistik}[v]||dashboard)()}
function current(){return document.querySelector('.nav-item.active')?.dataset.view||'dashboard'}
function markAction(view){if(view==='dashboard')document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view==='dashboard'));}
function handle(e){const route=e.target.closest?.('[data-suite-route]')?.dataset.suiteRoute;if(route){e.preventDefault();const b=document.querySelector(`.nav-item[data-view="${route}"]`);if(b){b.click()}else{markAction(route);renderView(route)}return}const act=e.target.closest?.('[data-action]')?.dataset.action;if(!act)return;const s=state();
if(act==='abcde-check'){const q=abcdeQuestions[Math.min(abcdeQuestions.length-1,s.abcdeIndex||0)],v=document.querySelector('input[name="abcde-answer"]:checked'),fb=document.getElementById('abcdeFeedback');if(!v){fb.innerHTML='<div class="suite-note suite-danger">Bitte eine Antwort auswählen.</div>';return}s.attempts.abcde=(s.attempts.abcde||0)+1;if(Number(v.value)!==q[4]){fb.innerHTML=`<div class="suite-note suite-danger">❌ Nicht korrekt. Trainingslösung: <b>${esc(q[2][q[4]])}</b></div>`;save(s);return}if((s.abcdeIndex||0)<abcdeQuestions.length-1){s.abcdeIndex++;save(s);renderView('abcde')}else{s.abcdeIndex=0;s.completed.abcde=true;save(s);shell('ABCDE abgeschlossen','TRAINING · ERLEDIGT','Alle fünf Schritte wurden korrekt bearbeitet.','<div class="suite-card learning-card"><div class="suite-note">✅ Das Modul ist abgeschlossen.</div><div class="suite-toolbar"><button class="suite-btn primary" data-suite-route="ausbildung">Zum Lernpfad</button><button class="suite-btn" data-suite-route="abcde">Noch einmal üben</button></div></div>')}}
if(act==='abcde-reset'){s.abcdeIndex=0;save(s);renderView('abcde');return}
if(act==='med-next'){const meds=window.RD_MEDS||[];if(!meds.length)return;const idx=(s.medIndex||0)%meds.length;if(!s.medSeen.includes(idx))s.medSeen.push(idx);s.medIndex=(idx+1)%meds.length;if(s.medSeen.length>=5&&s.medQuiz>=5)s.completed.medlernen=true;save(s);renderView('medlernen');return}
if(act==='med-check'){const meds=window.RD_MEDS||[],idx=(s.medIndex||0)%Math.max(1,meds.length),m=meds[idx],v=document.querySelector('input[name="med-answer"]:checked'),fb=document.getElementById('medFeedback');if(!v){fb.innerHTML='<div class="suite-note suite-danger">Bitte eine Antwort auswählen.</div>';return}s.medQuiz++;if(Number(v.value)===0)fb.innerHTML='<div class="suite-note">✅ Richtig.</div>';else fb.innerHTML=`<div class="suite-note suite-danger">❌ Die richtige Kategorie ist „${esc(m?.[1]||'Kategorie')}“.</div>`;if(s.medSeen.length>=5&&s.medQuiz>=5)s.completed.medlernen=true;save(s);return}
if(act==='hazard-check'){const c=hazardCases[(s.hazardIndex||0)%hazardCases.length],v=document.querySelector('input[name="hazard-answer"]:checked'),fb=document.getElementById('hazardFeedback');if(!v){fb.innerHTML='<div class="suite-note suite-danger">Bitte eine Antwort auswählen.</div>';return}s.hazardAnswered=Math.min(6,s.hazardAnswered+1);if(Number(v.value)===c.c)s.h.hazardCorrect=(s.hazardCorrect||0)+1;else fb.innerHTML='<div class="suite-note suite-danger">❌ '+esc(c.a[c.c])+'</div>';if(Number(v.value)===c.c)fb.innerHTML='<div class="suite-note">✅ Richtige Schwerpunktsetzung.</div>';s.hazardCorrect=s.h?.hazardCorrect||s.hazardCorrect||0;delete s.h; if(s.hazardAnswered>=6){if(s.hazardCorrect>=4)s.completed.gefahren=true;s.hazardIndex=0}else s.hazardIndex++;save(s);renderView('gefahren');return}
if(act==='hazard-reset'){s.hazardIndex=0;s.hazardAnswered=0;s.hazardCorrect=0;s.completed.gefahren=false;save(s);renderView('gefahren');return}
if(act==='psych-check'){const c=psychCases[(s.psychIndex||0)%psychCases.length],v=document.querySelector('input[name="psych-answer"]:checked'),fb=document.getElementById('psychFeedback');if(!v){fb.innerHTML='<div class="suite-note suite-danger">Bitte eine Antwort auswählen.</div>';return}s.psychAnswered=Math.min(psychCases.length,s.psychAnswered+1);if(Number(v.value)===c.c)s.psychCorrect++;fb.innerHTML=Number(v.value)===c.c?'<div class="suite-note">✅ Gute sicherheits- und kommunikationsorientierte Entscheidung.</div>':`<div class="suite-note suite-danger">❌ Besserer Ansatz: ${esc(c.a[c.c])}</div>`;if(s.psychAnswered>=psychCases.length){if(s.psychCorrect>=4)s.completed.psychiatrie=true;s.psychIndex=0}else s.psychIndex++;save(s);setTimeout(()=>renderView('psychiatrie'),350);return}
if(act==='knowledge-read'){const i=Number(e.target.closest('[data-index]')?.dataset.index);if(!Number.isInteger(i))return;if(!s.knowledgeRead.includes(i))s.knowledgeRead.push(i);if(s.knowledgeRead.length>=10)s.completed.wissensdatenbank=true;save(s);renderKnowledge();return}
if(act==='exam-next'){window.__examSession?.next();return}
if(act==='reset-learning'){localStorage.removeItem(STORE);renderView('dashboard');return}
}
function submit(e){if(e.target.id!=='docForm')return;e.preventDefault();if(!e.target.reportValidity())return;const s=state();s.docs++;s.completed.dokumentation=true;save(s);const fd=new FormData(e.target),rows=[['Fall',fd.get('fall')],['Zeit',fd.get('zeit')],['Ort',fd.get('ort')],['Meldebild',fd.get('meldung')],['Anamnese',fd.get('anamnese')],['Befunde',fd.get('befunde')],['Maßnahmen',fd.get('massnahmen')],['Übergabe',fd.get('uebergabe')]];document.getElementById('docResult').innerHTML=`<div class="suite-card learning-card"><div class="suite-panel-head"><h3>✅ Dokumentation abgeschlossen</h3><button class="suite-btn" data-action="print-doc">Drucken</button></div><table class="suite-table">${rows.map(r=>`<tr><th>${esc(r[0])}</th><td>${esc(r[1]||'—')}</td></tr>`).join('')}</table></div>`}
const oldRender=window.render;
window.render=function(){const v=current();if(['dashboard',...CORE.map(x=>x[0]),...TOOLS.map(x=>x[0])].includes(v)){renderView(v);return}oldRender()};
document.addEventListener('click',handle);
document.addEventListener('submit',submit);
document.addEventListener('input',e=>{if(e.target.id==='knowledgeSearch'||e.target.id==='knowledgeCat')renderKnowledge()});
document.addEventListener('change',e=>{if(e.target.id==='knowledgeCat')renderKnowledge()});
document.addEventListener('click',e=>{if(e.target.id==='print-doc'){window.print()}});
setTimeout(()=>window.render(),0);
})();
