(()=>{
  if(window.__rdLearningSuiteV4)return;
  window.__rdLearningSuiteV4=true;
  const app=document.getElementById('app');
  const STORE='rd-suite-progress-v2';
  const CORE=[
    ['abcde','🩺','ABCDE-Training','5 Schritte mit unmittelbarem Feedback'],
    ['dokumentation','📋','Einsatzdokumentation','Trainingsfall vollständig dokumentieren'],
    ['medlernen','💊','Medikamenten-Lernen','Karteikarten und Kurzquiz'],
    ['gefahren','🦺','Gefahren & Eigenschutz','6 Lagefälle sicher beurteilen'],
    ['psychiatrie','🧠','Psychiatrische Einsatzlagen','5 Kommunikations- und Sicherheitsfälle'],
    ['pruefung','🏆','Prüfungsmodus','10 Fragen, Bestehen ab 70 %'],
    ['wissensdatenbank','📚','Wissensdatenbank','10 Lernkarten aktiv festigen']
  ];
  const TOOLS=[
    ['ausbildung','🎓','Ausbildungsmodus','Lernpfad und Modulstatus'],
    ['suche','🔎','Globale Suche','Lern- und Intranet-Inhalte durchsuchen'],
    ['statistik','📊','Statistik & Fortschritt','Lernstand und Ergebnisse']
  ];
  const ABCDE=[
    ['A – Airway','Was gehört primär zu A?',['Atemweg und Schutzreflexe','Atemfrequenz','Blutdruck','Temperatur'],0],
    ['B – Breathing','Was gehört zu B?',['Atemarbeit und Atemfrequenz','Nur Puls','Nur Hautfarbe','Nur Gewicht'],0],
    ['C – Circulation','Was unterstützt die Kreislaufbeurteilung?',['Puls, Blutdruck, Haut und Blutung','Nur Temperatur','Nur Pupillen','Nur Schmerz'],0],
    ['D – Disability','Was gehört zu D?',['Bewusstsein und neurologische Auffälligkeiten','Nur Körpergröße','Nur Temperatur','Nur Medikamentenname'],0],
    ['E – Exposure','Was ergänzt die Untersuchung?',['Verletzungen, Temperatur und Umfeld','Nur Blutdruck','Nur Puls','Nur SpO₂'],0]
  ];
  const HAZARDS=[
    ['Verkehrsunfall auf Landstraße',['Fließender Verkehr','Instabiles Fahrzeug','Glassplitter'],'Was ist vor Patientenkontakt wichtig?',['Sicheren Standbereich wählen, Gefahren berücksichtigen und Unterstützung organisieren.','Direkt zur Fahrertür gehen.','Zuerst Dokumentation beginnen.'],0],
    ['Unbekannter Stoff im Keller',['Unbekannter Stoff','Mögliche Dämpfe','Enger Zugang'],'Welche Reaktion passt?',['Nicht ungeschützt vorgehen; Gefahrenbereich, PSA und zuständige Kräfte beachten.','Kurz hineingehen und identifizieren.','Patient sofort herausholen.'],0],
    ['Stromunfall in Werkstatt',['Elektrische Energie','Maschinen','Enge Umgebung'],'Was hat Priorität?',['Sichere Abschaltung/Annäherung nach lokalem Verfahren.','Patient sofort anfassen.','Nur Vitalwerte dokumentieren.'],0],
    ['Aggressive Person',['Fremdgefährdung','Publikum','Unklare Bewaffnung'],'Welche Taktik ist sinnvoll?',['Abstand, Rückzugsweg und Unterstützung/Polizei nach Lage.','Dicht herantreten und laut argumentieren.','Alle Teammitglieder gleichzeitig sprechen lassen.'],0],
    ['Wohnungsbrand',['Rauch','Hitze','Unübersichtlicher Innenraum'],'Was steht im Vordergrund?',['Eigenschutz und sichere Zusammenarbeit mit der Feuerwehr.','Ungesichert hineingehen.','Nur Personalien erheben.'],0],
    ['Gefahrgut-Transport',['Beschädigtes Fahrzeug','Unklare Kennzeichnung','Mögliche Kontamination'],'Was ist vor Annäherung wichtig?',['Gefahr erkennen, Abstand halten und geeignete Kräfte/Informationen organisieren.','Container öffnen.','Unmittelbar in den Nahbereich gehen.'],0]
  ];
  const PSYCH=[
    ['Akute Unruhe im Wohnraum','Mittel',['Patient laut und angespannt','Angehörige vor Ort','Rückzugsweg beachten'],'Was ist am ehesten deeskalierend?',['Abstand, ruhige Ansprache, klarer Ausweg und Unterstützung.','Konfrontativ beweisen, dass der Patient falsch liegt.','Mehrere Personen gleichzeitig sprechen lassen.'],0],
    ['Paranoide Wahrnehmung','Hoch',['Patient fühlt sich verfolgt','Spricht schnell','Keine sichtbare Waffe'],'Was ist sinnvoll?',['Ruhig bleiben, Abstand halten und nicht konfrontativ argumentieren.','Wahrnehmung lächerlich machen.','Ohne Erklärung näher kommen.'],0],
    ['Suizidale Krise','Hoch',['Konkrete Suizidgedanken','Gefährliche Gegenstände möglich','Angehörige vor Ort'],'Was ist zu priorisieren?',['Lage/Eigenschutz sichern, Unterstützung nachfordern und lokalen Krisenablauf folgen.','Risiko ignorieren und nur dokumentieren.','Patient allein lassen.'],0],
    ['Intoxikation mit Verhaltensauffälligkeit','Hoch',['Unklare Substanz','Verändertes Verhalten','Unübersichtliches Umfeld'],'Was gehört zur sicheren Ausgangslage?',['Abstand, Umfeld, Bewusstsein/Vitalfunktionen und Unterstützung beachten.','Nur Substanz erraten.','Patient unbeobachtet lassen.'],0],
    ['Angst-/Panikreaktion','Mittel',['Starke Angst','Schnelle Atmung','Ansprechbar'],'Wie kommunizieren?',['Ruhig, klar, respektvoll und strukturiert.','Drohungen einsetzen.','Patient ignorieren.'],0]
  ];
  const EXAM=[
    ['ABCDE','Welche Struktur unterstützt eine systematische Ersteinschätzung?',['ABCDE','Nur Blutdruck','Nur EKG','Nur Temperatur'],0],
    ['Eigenschutz','Was ist bei unklarer Gefahr wichtig?',['Lage/Gefahren und Eigenschutz','Sofort hineingehen','Nur dokumentieren','Nur Patientendaten'],0],
    ['Psychiatrie','Was unterstützt Deeskalation?',['Ruhige Kommunikation und Distanz','Konfrontation','Mehrere Stimmen gleichzeitig','Provokation'],0],
    ['Dokumentation','Was gehört in eine nachvollziehbare Dokumentation?',['Befunde, Zeiten, Maßnahmen und Verlauf','Nur Name','Nur Uhrzeit','Nur Diagnose'],0],
    ['Re-Evaluation','Was ist bei Veränderungen wichtig?',['Erneut strukturiert beurteilen','Nur einmal messen','Dokumentation beenden','Nicht mehr beobachten'],0],
    ['Anamnese','Welche Angabe ist besonders hilfreich?',['Beginn und Verlauf der Beschwerden','Nur Körpergröße','Nur Beruf','Nur Wohnort'],0],
    ['Übergabe','Was ist bei einer strukturierten Übergabe wichtig?',['Relevante Befunde, Verlauf und Maßnahmen','Nur Fahrzeugnummer','Nur Name','Nur Gewicht'],0],
    ['Hygiene','Was gehört grundsätzlich zur sicheren Versorgung?',['Situationsgerechte Hygiene und PSA','Keine Vorbereitung','Immer nur Handschuhe','Nur Fahrzeugdesinfektion'],0],
    ['MANV','Was gehört zu einem MANV-Konzept?',['Sichtung, Führung und Ressourcenstruktur','Nur Einzelpatientenversorgung','Nur Dokumentation','Nur Transport'],0],
    ['Ausbildung','Wofür dient Lernfortschritt?',['Gezieltes Wiederholen und Nachverfolgen des Lernstands','Nur Statistik','Nur Dekoration','Nur Prüfungsergebnisse'],0]
  ];
  const KNOWLEDGE=[
    ['ABCDE','ABCDE','Strukturierte Ersteinschätzung von A bis E.'],['Airway','ABCDE','A fokussiert auf Atemweg, Schutzreflexe und sichtbare Obstruktion.'],['Breathing','ABCDE','B umfasst Atemarbeit, Atemfrequenz, Oxygenierung und klinische Atemzeichen.'],['Circulation','ABCDE','C umfasst Puls, Blutdruck, Hautzeichen, Blutungen und Perfusion.'],['Disability','ABCDE','D umfasst Bewusstsein und neurologische Auffälligkeiten.'],['Exposure','ABCDE','E betrachtet Gesamtzustand, Verletzungen, Temperatur und Umfeld.'],['Eigenschutz','Sicherheit','Vor Patientenkontakt Lage, Gefahren, Rückzugsweg, PSA und Unterstützung prüfen.'],['Gasgeruch','Sicherheit','Gefahrenbereich beachten und nicht ungeschützt betreten; lokale Abläufe beachten.'],['Suizidale Krise','Psychiatrie','Eigengefährdung ernst nehmen, Lage sichern und lokalen Krisenablauf anwenden.'],['Dokumentation','Dokumentation','Zeitpunkte, Beschwerden, Befunde, Maßnahmen und Verlauf nachvollziehbar festhalten.'],['Übergabe','Dokumentation','Problem, relevante Befunde, Verlauf und erfolgte Maßnahmen strukturiert weitergeben.'],['Vitalwerte','Diagnostik','Vitalwerte sind Momentaufnahmen und sollten im Verlauf erneut bewertet werden.'],['Bewusstsein','Diagnostik','Bewusstseinslage beobachten und Veränderungen dokumentieren.'],['Schmerz','Diagnostik','Schmerz standardisiert erfassen und im Verlauf erneut bewerten.'],['Anaphylaxie','Notfallbild','Akute allergische Reaktion kann Atemweg, Atmung und Kreislauf betreffen; lokale SOP beachten.'],['Thoraxschmerz','Notfallbild','Beginn, Charakter, Begleitsymptome und Verlauf strukturiert erfassen.']
  ];
  const defaults={completed:{},attempts:{},abcdeIndex:0,medIndex:0,medSeen:[],medQuiz:0,hazardIndex:0,hazardAnswered:0,hazardCorrect:0,psychIndex:0,psychAnswered:0,psychCorrect:0,knowledgeRead:[],quizCorrect:0,quizTotal:0,examBest:0,examAttempts:0,docs:0};
  const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  function state(){let raw={};try{raw=JSON.parse(localStorage.getItem(STORE)||'{}')}catch{};const s=Object.assign({},defaults,raw);s.completed=Object.assign({},defaults.completed,raw.completed||raw.done||{});s.attempts=Object.assign({},defaults.attempts,raw.attempts||{});s.medSeen=Array.isArray(raw.medSeen)?raw.medSeen:[];s.knowledgeRead=Array.isArray(raw.knowledgeRead)?raw.knowledgeRead:[];return s}
  function save(s){localStorage.setItem(STORE,JSON.stringify(Object.assign({},s,{updatedAt:Date.now()})))}
  function progress(){const s=state(),done=CORE.filter(m=>s.completed[m[0]]).length;return{done,total:CORE.length,pct:Math.round(done*100/CORE.length)}}
  function shuffle(options,correct){const arr=options.map((text,index)=>({text,index}));for(let i=arr.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return{arr,correct:arr.findIndex(x=>x.index===correct)}}
  function choices(name,question,options,correct){const q=shuffle(options,correct);return `<div class="learning-question" data-correct="${q.correct}"><h2>${esc(question)}</h2><div class="suite-choice-list">${q.arr.map((x,i)=>`<label class="suite-choice"><input type="radio" name="${name}" value="${i}"><span>${esc(x.text)}</span></label>`).join('')}</div></div>`}
  function shell(eyebrow,title,desc,body){app.innerHTML=`<div class="suite-hero"><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${desc}</p></div>${body}`}
  function dashboard(){const s=state(),p=progress(),avg=s.quizTotal?Math.round(s.quizCorrect*100/s.quizTotal):0;app.innerHTML=`<div class="suite-hero learn-hero"><span class="eyebrow red">RD INTRANET · LERNZENTRUM</span><h1>Startseite – dein Lernzentrum.</h1><p>Alle Ausbildungsinhalte, Prüfungen und Lernfortschritte an einem Ort. Nur echte Lernleistungen verändern den Gesamtfortschritt.</p><div class="learn-hero-row"><div class="learn-hero-progress"><div class="learn-progress-meta"><span>Gesamtfortschritt</span><strong>${p.pct}%</strong></div><div class="suite-progress"><span style="width:${p.pct}%"></span></div><small>${p.done} von ${p.total} Lernmodulen abgeschlossen</small></div><button class="suite-btn primary" data-suite-route="ausbildung">🎓 Lernpfad öffnen</button></div></div><section class="suite-grid learn-stats"><div class="suite-stat"><small>Lernmodule</small><strong>${p.done}/${p.total}</strong><span>abgeschlossen</span></div><div class="suite-stat"><small>Quiz-Trefferquote</small><strong>${avg}%</strong><span>${s.quizCorrect}/${s.quizTotal} Antworten</span></div><div class="suite-stat"><small>Prüfungsbestwert</small><strong>${s.examBest}%</strong><span>${s.examAttempts} Versuch(e)</span></div><div class="suite-stat"><small>Dokumentationen</small><strong>${s.docs}</strong><span>Trainingsberichte</span></div></section><section class="learn-section"><div class="learn-section-head"><div><span class="eyebrow">LERNMODULE</span><h2>Dein Lernpfad</h2><p>Jedes Modul hat eine echte Abschlussbedingung.</p></div><button class="suite-btn" data-suite-route="statistik">📊 Statistik</button></div><div class="learn-module-grid">${CORE.map(m=>`<button class="learn-module ${s.completed[m[0]]?'done':''}" data-suite-route="${m[0]}"><span class="learn-module-icon">${m[1]}</span><div><div class="learn-module-title">${m[2]} ${s.completed[m[0]]?'<span class="suite-badge green">ERLEDIGT</span>':'<span class="suite-badge">OFFEN</span>'}</div><p>${m[3]}</p></div><span class="learn-arrow">›</span></button>`).join('')}</div></section><section class="learn-section"><div class="learn-section-head"><div><span class="eyebrow">WERKZEUGE</span><h2>Weitere Bereiche</h2><p>Suche, Lernpfad und Statistik unterstützen dich, zählen aber nicht als zusätzliche Prozentpunkte.</p></div></div><div class="learn-tools-grid">${TOOLS.map(m=>`<button class="learn-tool" data-suite-route="${m[0]}"><span>${m[1]}</span><div><b>${m[2]}</b><small>${m[3]}</small></div></button>`).join('')}</div></section>`}
  function abcde(){const s=state(),i=Math.min(ABCDE.length-1,Math.max(0,s.abcdeIndex||0)),q=ABCDE[i];shell('ABCDE · INTERAKTIV','ABCDE-Training','Beantworte alle fünf Schritte. Nur ein vollständiger korrekter Durchlauf markiert das Modul als erledigt.',`<div class="suite-card learning-card"><div class="learn-question-top"><span class="suite-badge red">Schritt ${i+1}/${ABCDE.length}</span><span class="suite-badge blue">${q[0]}</span></div>${choices('abcde-answer',q[1],q[2],q[3])}<div id="abcdeFeedback"></div><div class="suite-toolbar"><button class="suite-btn primary" data-action="abcde-check">Antwort prüfen</button><button class="suite-btn" data-action="abcde-reset">Neu starten</button></div></div>`)}
  function dokumentation(){const now=new Date();shell('DOKUMENTATION · TRAINING','Einsatzdokumentation','Ein vollständiger Trainingsbericht. Pflichtfelder werden vor dem Abschluss geprüft.',`<form id="docForm" class="suite-form learning-card"><div class="suite-form-row"><label>Einsatz/Fall<input name="fall" required value="Training-${Date.now().toString().slice(-5)}"></label><label>Zeit<input name="zeit" required value="${esc(now.toLocaleString('de-DE'))}"></label></div><div class="suite-form-row"><label>Ort<input name="ort" required placeholder="z. B. Wohnung / Straße"></label><label>Meldebild<input name="meldung" required placeholder="z. B. Dyspnoe"></label></div><label>Anamnese / Fremdanamnese<textarea name="anamnese" rows="4" required></textarea></label><label>ABCDE / Vitalwerte / Befunde<textarea name="befunde" rows="5" required></textarea></label><label>Maßnahmen / Verlauf<textarea name="massnahmen" rows="5" required></textarea></label><label>Übergabe / Transport / Abschluss<textarea name="uebergabe" rows="4" required></textarea></label><div class="suite-note">Trainingsdokumentation ohne reale Patientendaten. Für produktiven Einsatz ausschließlich geprüfte lokale Vorgaben verwenden.</div><button class="suite-btn primary" type="submit">📋 Bericht abschließen</button></form><div id="docResult"></div>`)}
  function medlernen(){const meds=window.RD_MEDS||[],s=state();if(!meds.length){shell('MEDIKAMENTE · LERNEN','Medikamenten-Lernen','Es sind keine Medikamentendaten geladen.','<div class="suite-note suite-danger">RD_MEDS ist leer oder nicht geladen.</div>');return}const idx=(s.medIndex||0)%meds.length,m=meds[idx],cat=m[1]||'Kategorie';shell('MEDIKAMENTE · KARTEIKARTEN','Medikamenten-Lernen',`${Math.min(5,s.medSeen.length)} von 5 Karten gesehen · ${Math.min(5,s.medQuiz)} von 5 Quizantworten.`,`<div class="suite-grid two"><article class="suite-card learning-card"><div class="learn-question-top"><span class="suite-badge blue">Karte ${idx+1}/${meds.length}</span><span class="suite-badge">${esc(cat)}</span></div><h2>${esc(m[0])}</h2><p class="learn-card-copy">${esc(m[2]||'Kein Beschreibungstext vorhanden.')}</p><div class="suite-note">Trainingsfokus: Name, Kategorie und Zweck verstehen. Keine Dosierungs- oder Applikationsanweisung.</div><button class="suite-btn primary" data-action="med-next">Karte als gelernt markieren →</button></article><article class="suite-card learning-card"><h3>Mini-Quiz</h3>${choices('med-answer','Welche Kategorie gehört zur aktuellen Karte?',[cat,'Diagnostik','Sicherheit'],0)}<div id="medFeedback"></div><button class="suite-btn green" data-action="med-check">Antwort prüfen</button></article></div>`)}
  function gefahren(){const s=state(),i=(s.hazardIndex||0)%HAZARDS.length,c=HAZARDS[i];shell('SICHERHEIT · FALLTRAINING','Gefahren & Eigenschutz',`Fall ${i+1}/${HAZARDS.length} · Mindestens 4 richtige Antworten schließen das Modul ab.`,`<div class="suite-grid two"><div class="suite-card learning-card"><span class="suite-badge red">Lage</span><h2>${esc(c[0])}</h2><div class="suite-chip-row">${c[1].map(x=>`<span class="suite-chip">⚠ ${esc(x)}</span>`).join('')}</div>${choices('hazard-answer',c[2],c[3],c[4])}<div id="hazardFeedback"></div><button class="suite-btn warn" data-action="hazard-check">Antwort prüfen</button></div><div class="suite-card"><div class="suite-panel-head"><h3>Fortschritt</h3><span class="suite-badge blue">${s.hazardAnswered}/6</span></div><div class="suite-list"><div class="suite-list-row"><span>Fälle</span><b>${s.hazardAnswered}/6</b></div><div class="suite-list-row"><span>Richtig</span><b>${s.hazardCorrect}</b></div><div class="suite-list-row"><span>Status</span><b>${s.completed.gefahren?'✅ Erledigt':'4/6 benötigt'}</b></div></div><button class="suite-btn" data-action="hazard-reset">Training zurücksetzen</button></div></div>`)}
  function psychiatrie(){const s=state(),i=(s.psychIndex||0)%PSYCH.length,c=PSYCH[i];shell('PSYCHIATRIE · FALLTRAINING','Psychiatrische Einsatzlagen',`Fall ${i+1}/${PSYCH.length} · Mindestens 4 von 5 richtige Antworten schließen das Modul ab.`,`<div class="suite-grid two"><div class="suite-card learning-card"><div class="learn-question-top"><span class="suite-badge ${c[1]==='Hoch'?'red':'amber'}">Risiko: ${esc(c[1])}</span></div><h2>${esc(c[0])}</h2><div class="suite-list">${c[2].map(x=>`<div class="suite-list-row">${esc(x)}</div>`).join('')}</div></div><div class="suite-card learning-card">${choices('psych-answer',c[3],c[4],c[5])}<div id="psychFeedback"></div><button class="suite-btn primary" data-action="psych-check">Antwort prüfen</button></div></div>`)}
  function ausbildung(){const p=progress(),s=state();shell('LERNPFAD · ÜBERSICHT','Ausbildungsmodus','Nur die sieben echten Lernmodule bestimmen den Prozentwert.',`<div class="suite-card learning-card"><div class="learn-progress-meta"><span>Gesamtfortschritt</span><strong>${p.pct}%</strong></div><div class="suite-progress"><span style="width:${p.pct}%"></span></div><p>${p.done}/${p.total} Lernmodule abgeschlossen</p></div><div class="learn-module-list">${CORE.map(m=>`<button class="learn-module ${s.completed[m[0]]?'done':''}" data-suite-route="${m[0]}"><span class="learn-module-icon">${m[1]}</span><div><b>${m[2]}</b><small>${m[3]}</small></div><span>${s.completed[m[0]]?'✅':'→'}</span></button>`).join('')}</div>`)}
  function pruefung(){let questions=EXAM.slice().sort(()=>Math.random()-.5),i=0,answers=[];const draw=()=>{const q=questions[i];shell('ABSCHLUSSPRÜFUNG','Prüfungsmodus',`Frage ${i+1}/${questions.length} · Bestehen ab 70 %.`,`<div class="suite-card learning-card">${choices('exam-answer',q[1],q[2],q[3])}<div id="examFeedback"></div><button class="suite-btn primary" data-action="exam-next">Antwort übernehmen</button></div>`)};draw();window.__examSession={next:()=>{const card=document.querySelector('.learning-question'),v=document.querySelector('input[name="exam-answer"]:checked'),fb=document.getElementById('examFeedback');if(!v){if(fb)fb.innerHTML='<div class="suite-note suite-danger">Bitte eine Antwort auswählen.</div>';return}const ok=Number(v.value)===Number(card.dataset.correct);answers.push(ok);const s=state();s.quizTotal++;if(ok)s.quizCorrect++;save(s);if(i<questions.length-1){i++;draw();return}const score=Math.round(answers.filter(Boolean).length*100/questions.length),st=state();st.examAttempts++;st.examBest=Math.max(st.examBest,score);if(score>=70)st.completed.pruefung=true;save(st);shell(score>=70?'PRÜFUNG · BESTANDEN':'PRÜFUNG · WIEDERHOLEN',score>=70?'Prüfung bestanden':'Prüfung noch nicht bestanden',`${answers.filter(Boolean).length}/${questions.length} richtig · ${score}%`,`<div class="suite-card learning-card"><div class="suite-kv"><div><small>Ergebnis</small><b>${score}%</b></div><div><small>Grenze</small><b>70%</b></div><div><small>Status</small><b>${score>=70?'✅ BESTANDEN':'↻ WIEDERHOLEN'}</b></div></div><div class="suite-toolbar"><button class="suite-btn primary" data-suite-route="pruefung">Neue Prüfung</button><button class="suite-btn" data-suite-route="statistik">Statistik</button></div></div>`)} }}
  function wissensdatenbank(){const s=state();shell('WISSEN · LERNKARTEN','Wissensdatenbank',`${Math.min(10,s.knowledgeRead.length)} von 10 Lernkarten gelernt.`,`<div class="suite-toolbar"><div class="grow"><input id="knowledgeSearch" placeholder="Begriff oder Thema suchen …"></div><select id="knowledgeCat"><option value="">Alle Kategorien</option>${[...new Set(KNOWLEDGE.map(x=>x[1]))].map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div id="knowledgeResults" class="learn-knowledge-grid"></div>`);renderKnowledge()}
  function renderKnowledge(){const out=document.getElementById('knowledgeResults');if(!out)return;const s=state(),q=(document.getElementById('knowledgeSearch')?.value||'').toLowerCase(),cat=document.getElementById('knowledgeCat')?.value||'';out.innerHTML=KNOWLEDGE.filter(x=>(!q||x.join(' ').toLowerCase().includes(q))&&(!cat||x[1]===cat)).map((x,i)=>{const done=s.knowledgeRead.includes(i);return `<article class="learn-knowledge-card"><div><span class="suite-badge blue">${esc(x[1])}</span><h3>${esc(x[0])}</h3><p>${esc(x[2])}</p></div><button class="suite-btn ${done?'green':''}" data-action="knowledge-read" data-index="${i}">${done?'✓ Gelernt':'Als gelernt markieren'}</button></article>`}).join('')||'<div class="suite-note">Keine Treffer.</div>'}
  function suche(){const meds=(window.RD_MEDS||[]).map(m=>({t:m[0],c:'Medikament',d:m[2]||'',r:'medlernen'})),cases=(window.RD_DATA?.common||[]).map(x=>({t:x.title,c:x.cat||'Notfallbild',d:x.desc||'',r:'notfallbilder'})),know=KNOWLEDGE.map(x=>({t:x[0],c:x[1],d:x[2],r:'wissensdatenbank'})),all=[...know,...meds,...cases];shell('SUCHEN · ALLES FINDEN','Globale Suche','Treffer erscheinen sofort beim Tippen.',`<div class="suite-card search-card"><input id="globalSearchFull" class="learn-search-input" autofocus placeholder="z. B. Atemnot, Eigenschutz, Medikament …"><small id="searchCount"></small></div><div id="globalResults" class="suite-search-results"></div>`);const go=()=>{const q=(document.getElementById('globalSearchFull').value||'').trim().toLowerCase(),r=q?all.filter(x=>(x.t+' '+x.c+' '+x.d).toLowerCase().includes(q)).slice(0,80):[];document.getElementById('searchCount').textContent=q?`${r.length} Treffer`:'Suchbegriff eingeben';document.getElementById('globalResults').innerHTML=r.length?r.map(x=>`<button class="suite-search-item" data-suite-route="${x.r}"><b>${esc(x.t)}</b><span class="suite-badge blue">${esc(x.c)}</span><small>${esc(x.d)}</small></button>`).join(''):(q?'<div class="suite-note">Keine Treffer.</div>':'<div class="suite-note">Noch keine Suche gestartet.</div>')};document.getElementById('globalSearchFull').addEventListener('input',go);go()}
  function statistik(){const s=state(),p=progress(),avg=s.quizTotal?Math.round(s.quizCorrect*100/s.quizTotal):0;app.innerHTML=`<div class="suite-hero"><span class="eyebrow">STATISTIK · LERNFORTSCHRITT</span><h1>Dein Lernstand</h1><p>Prozentwerte basieren nur auf den sieben echten Lernmodulen.</p></div><div class="suite-grid learn-stats"><div class="suite-stat"><small>Gesamt</small><strong>${p.pct}%</strong><span>${p.done}/${p.total} Module</span></div><div class="suite-stat"><small>Quiz</small><strong>${avg}%</strong><span>${s.quizCorrect}/${s.quizTotal}</span></div><div class="suite-stat"><small>Prüfung</small><strong>${s.examBest}%</strong><span>${s.examAttempts} Versuche</span></div><div class="suite-stat"><small>Dokumentation</small><strong>${s.docs}</strong><span>Berichte</span></div></div><div class="suite-card learning-card"><div class="suite-panel-head"><h3>Modulstatus</h3><span class="suite-badge blue">${p.done}/${p.total}</span></div><div class="learn-status-table">${CORE.map(m=>`<div><span>${m[1]} ${m[2]}</span><b class="${s.completed[m[0]]?'ok':''}">${s.completed[m[0]]?'ERLEDIGT':'OFFEN'}</b></div>`).join('')}</div><div class="suite-toolbar"><button class="suite-btn" data-action="reset-learning">Lernstand zurücksetzen</button><button class="suite-btn" data-suite-route="ausbildung">Lernpfad öffnen</button></div></div>`}
  function view(v){return ({dashboard,abcde,dokumentation,medlernen,gefahren,psychiatrie,ausbildung,pruefung,wissensdatenbank,suche,statistik}[v]||dashboard)()}
  const previousRender=window.render;
  window.render=function(){const v=document.querySelector('.nav-item.active')?.dataset.view||'dashboard';if(['dashboard',...CORE.map(x=>x[0]),...TOOLS.map(x=>x[0])].includes(v))return view(v);return previousRender()}
  function onAction(e){const route=e.target.closest?.('[data-suite-route]')?.dataset.suiteRoute;if(route){e.preventDefault();const b=document.querySelector(`.nav-item[data-view="${route}"]`);if(b)b.click();else view(route);return}const action=e.target.closest?.('[data-action]')?.dataset.action;if(!action)return;const s=state();
    if(action==='abcde-check'){const card=document.querySelector('.learning-question'),v=document.querySelector('input[name="abcde-answer"]:checked'),fb=document.getElementById('abcdeFeedback');if(!v){fb.textContent='Bitte eine Antwort auswählen.';return}s.attempts.abcde=(s.attempts.abcde||0)+1;if(Number(v.value)!==Number(card.dataset.correct)){fb.innerHTML='<div class="suite-note suite-danger">❌ Noch nicht richtig. Lies den Schritt erneut.</div>';save(s);return}if((s.abcdeIndex||0)<ABCDE.length-1){s.abcdeIndex++;save(s);abcde()}else{s.abcdeIndex=0;s.completed.abcde=true;save(s);shell('TRAINING · ERLEDIGT','ABCDE abgeschlossen','Alle fünf Schritte korrekt bearbeitet.','<div class="suite-card learning-card"><div class="suite-note">✅ Modul abgeschlossen.</div><div class="suite-toolbar"><button class="suite-btn primary" data-suite-route="ausbildung">Zum Lernpfad</button></div></div>')}return}
    if(action==='abcde-reset'){s.abcdeIndex=0;save(s);abcde();return}
    if(action==='med-check'){const card=document.querySelector('.learning-question'),v=document.querySelector('input[name="med-answer"]:checked'),fb=document.getElementById('medFeedback');if(!v){fb.textContent='Bitte eine Antwort auswählen.';return}s.medQuiz++;const ok=Number(v.value)===Number(card.dataset.correct);s.quizTotal++;if(ok){s.quizCorrect++;fb.innerHTML='<div class="suite-note">✅ Richtig.</div>'}else fb.innerHTML='<div class="suite-note suite-danger">❌ Nicht korrekt. Wiederhole die Karte.</div>';if(s.medSeen.length>=5&&s.medQuiz>=5)s.completed.medlernen=true;save(s);return}
    if(action==='med-next'){const meds=window.RD_MEDS||[];if(!meds.length)return;const idx=(s.medIndex||0)%meds.length;if(!s.medSeen.includes(idx))s.medSeen.push(idx);s.medIndex=(idx+1)%meds.length;if(s.medSeen.length>=5&&s.medQuiz>=5)s.completed.medlernen=true;save(s);medlernen();return}
    if(action==='hazard-check'){const card=document.querySelector('.learning-question'),v=document.querySelector('input[name="hazard-answer"]:checked'),fb=document.getElementById('hazardFeedback');if(!v){fb.textContent='Bitte eine Antwort auswählen.';return}const ok=Number(v.value)===Number(card.dataset.correct);s.hazardAnswered++;if(ok)s.hazardCorrect++;fb.innerHTML=ok?'<div class="suite-note">✅ Richtige Schwerpunktsetzung.</div>':'<div class="suite-note suite-danger">❌ Eigenschutz und Gefahrenbereich haben Vorrang.</div>';if(s.hazardAnswered>=HAZARDS.length){s.completed.gefahren=s.hazardCorrect>=4;s.hazardIndex=0}else s.hazardIndex++;save(s);gefahren();return}
    if(action==='hazard-reset'){s.hazardIndex=0;s.hazardAnswered=0;s.hazardCorrect=0;s.completed.gefahren=false;save(s);gefahren();return}
    if(action==='psych-check'){const card=document.querySelector('.learning-question'),v=document.querySelector('input[name="psych-answer"]:checked'),fb=document.getElementById('psychFeedback');if(!v){fb.textContent='Bitte eine Antwort auswählen.';return}const ok=Number(v.value)===Number(card.dataset.correct);s.psychAnswered++;if(ok)s.psychCorrect++;fb.innerHTML=ok?'<div class="suite-note">✅ Gute sicherheits- und kommunikationsorientierte Entscheidung.</div>':'<div class="suite-note suite-danger">❌ Prüfe Deeskalation und Eigenschutz erneut.</div>';if(s.psychAnswered>=PSYCH.length){s.completed.psychiatrie=s.psychCorrect>=4;s.psychIndex=0}else s.psychIndex++;save(s);psychiatrie();return}
    if(action==='knowledge-read'){const i=Number(e.target.closest('[data-index]')?.dataset.index);if(!Number.isInteger(i))return;if(!s.knowledgeRead.includes(i))s.knowledgeRead.push(i);if(s.knowledgeRead.length>=10)s.completed.wissensdatenbank=true;save(s);renderKnowledge();return}
    if(action==='exam-next'){window.__examSession?.next();return}
    if(action==='reset-learning'){localStorage.removeItem(STORE);dashboard();return}
    if(action==='print-doc'){window.print();return}
  }
  function onSubmit(e){if(e.target.id!=='docForm')return;e.preventDefault();if(!e.target.reportValidity())return;const s=state();s.docs++;s.completed.dokumentation=true;save(s);const fd=new FormData(e.target),rows=[['Fall',fd.get('fall')],['Zeit',fd.get('zeit')],['Ort',fd.get('ort')],['Meldebild',fd.get('meldung')],['Anamnese',fd.get('anamnese')],['Befunde',fd.get('befunde')],['Maßnahmen',fd.get('massnahmen')],['Übergabe',fd.get('uebergabe')]];document.getElementById('docResult').innerHTML=`<div class="suite-card learning-card"><div class="suite-panel-head"><h3>✅ Dokumentation abgeschlossen</h3><button class="suite-btn" data-action="print-doc">Drucken</button></div><table class="suite-table">${rows.map(r=>`<tr><th>${esc(r[0])}</th><td>${esc(r[1]||'—')}</td></tr>`).join('')}</table></div>`}
  document.addEventListener('click',onAction);
  document.addEventListener('submit',onSubmit);
  document.addEventListener('input',e=>{if(e.target.id==='knowledgeSearch')renderKnowledge()});
  document.addEventListener('change',e=>{if(e.target.id==='knowledgeCat')renderKnowledge()});
  setTimeout(()=>window.render(),0);
})();
