/* Stable checklist UX controller. Loaded after checklists.js. One capture-phase handler, explicit Next navigation. */
(()=>{
  'use strict';
  const root=()=>document.getElementById('app');
  const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const key=id=>'rd-checklist-ui-'+id;
  const valid=id=>window.RD_CHECKLISTS&&window.RD_CHECKLISTS[id]&&Array.isArray(window.RD_CHECKLISTS[id].questions);
  let activeId=null,activeIndex=0,resultView=false;
  const read=id=>{const n=window.RD_CHECKLISTS[id].questions.length;try{const x=JSON.parse(localStorage.getItem(key(id))||'{}');const a=Array(n).fill(null);if(Array.isArray(x.answers))x.answers.slice(0,n).forEach((v,i)=>{if(Number.isInteger(v)&&v>=0&&v<window.RD_CHECKLISTS[id].questions[i].answers.length)a[i]=v});return a}catch{return Array(n).fill(null)}};
  const save=(id,a)=>{try{localStorage.setItem(key(id),JSON.stringify({answers:a}))}catch{}};
  const answered=a=>a.filter(v=>v!==null).length;
  const crumb=t=>{const e=document.getElementById('breadcrumbCurrent');if(e)e.textContent=t};
  const medBlock=names=>Array.isArray(names)&&names.length?`<section class="clx-panel clx-meds"><div class="clx-panel-title">💊 Medikamentenbezug</div><p>Nur Registerverweis für Ausbildung/RP. Keine Dosierung oder eigenständige Therapieanweisung.</p><div class="clx-med-grid">${names.map(n=>`<button type="button" class="clx-med" data-stable-med="${esc(n)}"><strong>${esc(n)}</strong><small>Im Medikamentenregister prüfen</small></button>`).join('')}</div></section>`:'';
  function list(){
    activeId=null;activeIndex=0;resultView=false;crumb('Checklisten');const r=root();if(!r)return;
    r.innerHTML=`<div class="view-title"><div><span class="eyebrow red">CHECKLISTEN</span><h1>Geführte Einsatzabfragen</h1><p>Frage für Frage beantworten, kritische Punkte erkennen und am Ende den priorisierten Abschluss anzeigen.</p></div></div><div class="category-grid checklist-enhanced-grid">${Object.entries(RD_CHECKLISTS).map(([id,c])=>{const a=read(id),done=answered(a),pct=Math.round(done/c.questions.length*100);return `<button type="button" class="panel checklist-card clx-card" data-stable-open="${esc(id)}"><div class="clx-card-head"><span class="clx-icon">✓</span><h3>${esc(id)}</h3></div><p>${esc(c.desc||'Geführte Checkliste')}</p><div class="clx-progress"><span>${done}/${c.questions.length} Fragen</span><b>${pct}%</b></div><div class="clx-track"><i style="width:${pct}%"></i></div><span class="clx-open">Abfrage starten / fortsetzen →</span></button>`}).join('')}</div>`;
  }
  function detail(){
    const c=RD_CHECKLISTS[activeId];if(!c)return list();const a=read(activeId),total=c.questions.length;
    if(a.every(v=>v!==null)){resultView=true;return result()}
    if(activeIndex<0||activeIndex>=total)activeIndex=Math.max(0,a.findIndex(v=>v===null));
    const q=c.questions[activeIndex],sel=a[activeIndex],lvl=sel===null?'normal':q.answers[sel].level;crumb(`${activeId} / Abfrage ${activeIndex+1}`);const r=root();if(!r)return;
    const steps=c.questions.map((x,i)=>`<button type="button" class="clx-step ${i===activeIndex?'active ':''}${a[i]===null?'':x.answers[a[i]].level}" data-stable-jump="${i}"><span>${i+1}</span><strong>${esc(x.title)}</strong><small>${a[i]===null?'offen':esc(x.answers[a[i]].label)}</small></button>`).join('');
    const answers=q.answers.map((x,i)=>`<button type="button" class="clx-answer ${sel===i?'selected ':''}${x.level}" data-stable-answer="${i}"><strong>${esc(x.label)}</strong><small>${x.level==='critical'?'kritisch – sofort priorisieren':x.level==='warning'?'auffällig / unklar – weiter prüfen':'unauffällig / planmäßig'}</small></button>`).join('');
    const hint=sel===null?`<span>💡 ${esc(q.hint)}</span>`:lvl==='critical'?`<span>🚨 <b>Kritischer Punkt:</b> ${esc(q.hint)}</span>`:lvl==='warning'?`<span>⚠ <b>Auffälliger / unklarer Punkt:</b> ${esc(q.hint)}</span>`:`<span>✓ ${esc(q.hint)}</span>`;
    const done=answered(a),pct=Math.round(done/total*100),status=sel===null?'OFFEN':lvl==='critical'?'KRITISCH':lvl==='warning'?'ACHTUNG':'OK';
    r.innerHTML=`<div class="view-title"><div><span class="eyebrow red">CHECKLISTE / ${activeIndex+1} VON ${total}</span><h1>${esc(activeId)}</h1><p>${esc(c.desc||'Geführte Abfrage')}</p></div><button type="button" class="back" data-stable-back>← Übersicht</button></div><div class="clx-layout"><aside class="clx-sidebar clx-panel"><div class="clx-panel-title">Fragenübersicht</div><div class="clx-steps">${steps}</div><div class="clx-mini"><span>Fortschritt</span><b>${done}/${total} · ${pct}%</b><div class="clx-track"><i style="width:${pct}%"></i></div></div></aside><div class="clx-main"><section class="clx-panel clx-question ${lvl==='critical'?'is-critical':lvl==='warning'?'is-warning':''}"><div class="clx-question-top"><span class="clx-number">FRAGE ${activeIndex+1}</span><span class="clx-status ${lvl}">${status}</span></div><h2>${esc(q.title)}</h2><p class="clx-qtext">${esc(q.text)}</p><div class="clx-hint">${hint}</div><div class="clx-answers">${answers}</div><div class="clx-actions"><button type="button" class="secondary" data-stable-prev ${activeIndex===0?'disabled':''}>← Zurück</button><button type="button" class="primary" data-stable-next ${sel===null?'disabled':''}>${activeIndex===total-1?'Auswertung anzeigen':'Nächste Frage →'}</button></div></section>${medBlock(c.meds)}</div></div>`;
  }
  function result(){
    const c=RD_CHECKLISTS[activeId],a=read(activeId);resultView=true;crumb(`${activeId} / Auswertung`);const r=root();if(!r)return;const critical=[],warn=[];
    c.questions.forEach((q,i)=>{if(a[i]===null)warn.push([i,q,'Offen']);else if(q.answers[a[i]].level==='critical')critical.push([i,q,q.answers[a[i]].label]);else if(q.answers[a[i]].level==='warning')warn.push([i,q,q.answers[a[i]].label])});
    r.innerHTML=`<div class="view-title"><div><span class="eyebrow red">ABFRAGE ABGESCHLOSSEN</span><h1>${esc(activeId)} – Was jetzt?</h1><p>Priorisierte Ausbildungs-/RP-Orientierung. Lokale SOPs, Algorithmen und fachliche Anordnungen haben Vorrang.</p></div><button type="button" class="back" data-stable-back>← Übersicht</button></div><div class="clx-result-grid"><section class="clx-panel ${critical.length?'is-critical':''}"><div class="clx-panel-title">🚨 P1 · Sofort prüfen</div>${critical.length?critical.map(([i,q,l])=>`<div class="clx-result-row critical"><span>!</span><div><strong>${esc(q.title)}</strong><small>Antwort: ${esc(l)} · lokalen Notfall-/SOP-Pfad prüfen</small></div></div>`).join(''):'<div class="clx-ok">Keine kritisch markierte Antwort.</div>'}</section><section class="clx-panel"><div class="clx-panel-title">🟠 P2 · Auffällig / offen</div>${warn.length?warn.map(([i,q,l])=>`<div class="clx-result-row warning"><span>!</span><div><strong>${esc(q.title)}</strong><small>${esc(l)} · Kontext und Verlauf prüfen</small></div></div>`).join(''):'<div class="clx-ok">Keine zusätzlichen Warnpunkte.</div>'}</section><section class="clx-panel"><div class="clx-panel-title">✅ P3/P4 · Maßnahmen und Abschluss</div>${(c.plan||[]).map((p,i)=>`<div class="clx-result-row"><span>${i+1}</span><div><strong>${esc(p[0])}</strong><small>${esc(p[1])}</small></div></div>`).join('')}</section></div><section class="clx-panel clx-full"><div class="clx-panel-title">📋 Fragenprotokoll – anklickbar</div><div class="clx-result-grid inner">${c.questions.map((q,i)=>`<button type="button" class="clx-log ${a[i]===null?'warning':q.answers[a[i]].level}" data-stable-jump="${i}"><span>${i+1}</span><div><strong>${esc(q.title)}</strong><small>${a[i]===null?'Offen':esc(q.answers[a[i]].label)}</small></div></button>`).join('')}</div></section>${medBlock(c.meds)}<div class="clx-actions"><button type="button" class="secondary" data-stable-reset>↻ Abfrage zurücksetzen</button><button type="button" class="primary" data-stable-back>← Zur Checkliste</button></div>`;
  }
  function route(e){
    const t=e.target&&e.target.closest?e.target.closest('[data-stable-open],[data-stable-back],[data-stable-jump],[data-stable-answer],[data-stable-prev],[data-stable-next],[data-stable-reset],[data-stable-med]'):null;if(!t)return;e.preventDefault();e.stopImmediatePropagation();
    if(t.hasAttribute('data-stable-open')){activeId=t.getAttribute('data-stable-open');const a=read(activeId),first=a.findIndex(v=>v===null);activeIndex=first===-1?0:first;resultView=first===-1;resultView?result():detail();return}
    if(t.hasAttribute('data-stable-back')){list();return}
    if(t.hasAttribute('data-stable-jump')){activeIndex=Math.max(0,Math.min(Number(t.getAttribute('data-stable-jump'))||0,RD_CHECKLISTS[activeId].questions.length-1));resultView=false;detail();return}
    if(t.hasAttribute('data-stable-answer')){const a=read(activeId),i=Number(t.getAttribute('data-stable-answer')),q=RD_CHECKLISTS[activeId].questions[activeIndex];if(Number.isInteger(i)&&q.answers[i]){a[activeIndex]=i;save(activeId,a);detail();}return}
    if(t.hasAttribute('data-stable-prev')){activeIndex=Math.max(0,activeIndex-1);detail();return}
    if(t.hasAttribute('data-stable-next')){const a=read(activeId);if(a[activeIndex]===null)return;if(activeIndex>=RD_CHECKLISTS[activeId].questions.length-1){resultView=true;result();}else{activeIndex++;detail();}return}
    if(t.hasAttribute('data-stable-reset')){save(activeId,Array(RD_CHECKLISTS[activeId].questions.length).fill(null));activeIndex=0;resultView=false;detail();return}
    if(t.hasAttribute('data-stable-med')){const name=t.getAttribute('data-stable-med'),nav=document.querySelector('.nav-item[data-view="medikamente"]');if(nav){window.__checklistMedTarget=name;nav.click();setTimeout(()=>{const input=document.getElementById('medSearch');if(input){input.value=name;input.dispatchEvent(new Event('input',{bubbles:true}));}},0)}return}
  }
  function bind(){const r=root();if(!r||r.__rdStableChecklistBound)return;r.__rdStableChecklistBound=true;r.addEventListener('click',route,true);}
  window.renderChecklisten=()=>{bind();if(activeId&&valid(activeId)){resultView?result():detail()}else list();};
  bind();
  if(typeof currentView!=='undefined'&&currentView==='checklisten')window.renderChecklisten();
})();
