/* Cleaner question wording for the interactive checklist view. */
(()=>{
  const copy={
    'Eigenschutz':'Kann die Einsatzstelle sicher betreten und bearbeitet werden, ohne Patient, Team oder Dritte zu gefährden?',
    'Reaktionslage':'Reagiert der Patient adäquat auf Ansprache und entspricht die Vigilanz dem erwartbaren Zustand?',
    'Atemweg':'Ist der Atemweg aktuell frei und bestehen keine Hinweise auf eine drohende Verlegung?',
    'Atmung':'Ist die Atmung ausreichend und bestehen keine relevanten Auffälligkeiten der Atemarbeit?',
    'Kreislauf':'Wirkt die Kreislaufsituation stabil oder gibt es Hinweise auf relevante Minderperfusion bzw. Instabilität?',
    'Blutung':'Besteht aktuell eine relevante äußere Blutung oder ein begründeter Verdacht auf relevanten Blutverlust?',
    'Neurologie':'Bestehen neue neurologische Auffälligkeiten oder eine relevante Veränderung der Vigilanz?',
    'Vitalwerte':'Sind die für die aktuelle Situation relevanten Vitalparameter erhoben, bewertet und zeitlich nachvollziehbar dokumentiert?',
    'Re-Evaluation':'Wurde nach einer relevanten Veränderung oder Maßnahme erneut systematisch beurteilt?',
    'Übergabebereitschaft':'Sind Zeitverlauf, wesentliche Befunde, Veränderungen und offene Probleme für die Übergabe nachvollziehbar dokumentiert?',
    'Bewusstsein':'Ist die Person nicht ansprechbar bzw. zeigt sie keine adäquate Reaktion?',
    'Alarmierung':'Sind nach eurem lokalen Ablauf die erforderlichen Ressourcen alarmiert und ist die weitere Versorgung organisiert?',
    'Reanimationsteam':'Sind im Team klare Rollen, Zuständigkeiten und Kommunikationswege festgelegt?',
    'Defibrillation':'Ist der Defibrillator/AED verfügbar und nach lokalem Reanimationsalgorithmus einsatzbereit?',
    'Atemweg / Beatmung':'Ist die lokale Strategie für Atemweg und Beatmung festgelegt und im Team abgestimmt?',
    'Reversible Ursachen':'Werden reversible Ursachen nach dem gültigen lokalen Reanimationsalgorithmus systematisch berücksichtigt?',
    'Zeitpunkte':'Sind Beginn, relevante Rhythmusanalysen, Zustandsänderungen und weitere Schlüsselpunkte dokumentiert?',
    'Situation':'Kann das aktuelle Hauptproblem in einem kurzen, eindeutigen Satz benannt werden?',
    'Zeitverlauf':'Sind Beginn, Verlauf und entscheidende Zeitpunkte möglichst genau bekannt und dokumentiert?',
    'Anamnese':'Sind relevante Vorerkrankungen, Dauermedikation und der bisherige Verlauf erhoben?',
    'Allergien':'Sind relevante Allergien bzw. Unverträglichkeiten bekannt oder als unbekannt dokumentiert?',
    'Befunde':'Sind die wesentlichen Untersuchungsbefunde und relevanten Vitalwerte nachvollziehbar dokumentiert?',
    'Verlauf':'Sind relevante Veränderungen während des Einsatzes zeitlich nachvollziehbar festgehalten?',
    'Maßnahmen':'Sind bereits durchgeführte Maßnahmen und deren Zeitpunkt nachvollziehbar dokumentiert?',
    'Reaktion':'Ist festgehalten, wie sich der Patient nach relevanten Maßnahmen oder im Verlauf verändert hat?',
    'Risiken':'Sind aktuelle Risiken, Warnzeichen oder offene Probleme ausdrücklich benannt?',
    'Empfehlung':'Ist klar formuliert, was als Nächstes nach lokalem Ablauf bzw. Anordnung geklärt werden muss?',
    'Rückfragen':'Sind offene Punkte geklärt und wurde die Möglichkeit für Rückfragen bei der Übergabe berücksichtigt?',
    'Dokumentation':'Ist der aktuelle Zustand und die erfolgte Übergabe vollständig dokumentiert?',
    'Mechanismus':'Ist der Unfall-/Ereignismechanismus nachvollziehbar und mit möglichen Verletzungsmustern abgeglichen?',
    'Verletzungsmuster':'Sind relevante Verletzungen systematisch erfasst und nach Priorität eingeordnet?',
    'Begleitverletzungen':'Wurde nach der Erstversorgung erneut nach übersehenen Begleitverletzungen gesucht?',
    'Wärmeerhalt':'Ist der Wärmeerhalt ausreichend berücksichtigt und weiterer Wärmeverlust vermieden?',
    'Schmerz':'Sind Schmerzstärke, Lokalisation, Charakter und Verlauf nachvollziehbar dokumentiert?',
    'Alter / Gewicht':'Sind Alter und ein für den lokalen Ablauf geeignetes Gewicht bekannt oder entsprechend als unsicher dokumentiert?',
    'Verhalten':'Ist das Verhalten altersgerecht bzw. hat sich das Verhalten gegenüber dem Ausgangszustand relevant verändert?',
    'Kreislauf / Perfusion':'Gibt es Hinweise auf eine auffällige Perfusion oder Kreislaufverschlechterung?',
    'Fremdanamnese':'Liegen relevante Angaben von Eltern, Begleitpersonen oder anderen Zeugen zum Verlauf vor?',
    'Vorerkrankungen':'Sind relevante Vorerkrankungen und Dauermedikation bekannt?',
    'Trink-/Essverhalten':'Besteht eine relevante Veränderung von Trinken, Essen oder Ausscheidungen?',
    'Fieber / Infekt':'Gibt es Hinweise auf einen Infekt mit relevant verändertem Allgemeinzustand oder Verlauf?',
    'Sicherheit / Umfeld':'Gibt es im Umfeld relevante Sicherheits-, Betreuungs- oder Kinderschutzaspekte?',
    'Schwangerschaftswoche':'Ist die Schwangerschaftswoche sicher bekannt oder plausibel eingegrenzt?',
    'Geburtsphase':'Ist der aktuelle Geburtsfortschritt einschließlich Wehen und bisherigem Verlauf nachvollziehbar?',
    'Mutter – Zustand':'Ist die Mutter aktuell hinsichtlich Bewusstsein, Atmung und Kreislauf stabil?',
    'Wehen / Verlauf':'Sind Beginn, Häufigkeit und Verlauf der aktuellen Wehen bzw. Beschwerden nachvollziehbar?',
    'Kind':'Ist der aktuelle Zustand des Neugeborenen nach lokalem Ablauf erfasst?',
    'Substanz':'Ist bekannt, welche Substanz bzw. welches Produkt beteiligt war?',
    'Menge & Zeitpunkt':'Sind ungefähre Menge und Zeitpunkt der Exposition bekannt?',
    'Applikationsweg':'Ist bekannt, auf welchem Weg die Substanz aufgenommen bzw. die Exposition erfolgt ist?',
    'Bewusstsein & Vitalfunktionen':'Sind Bewusstseinslage, Atmung, Kreislauf und Verlauf aktuell beurteilt?',
    'Eigengefährdung':'Bestehen Hinweise auf aktuelle Selbstgefährdung oder eine entsprechende konkrete Absicht?',
    'Fremdgefährdung':'Bestehen Hinweise auf aktuelle Fremdgefährdung oder gefährliche Impulsdurchbrüche?',
    'Kooperation':'Kann der Patient ausreichend kooperieren oder werden zusätzliche Sicherheitsmaßnahmen benötigt?',
    'Anamnese / Umfeld':'Sind relevante Vorgeschichte, Substanzen, Medikamente und Fremdanamnese erhoben?',
  };
  function apply(){document.querySelectorAll('.clx-question .clx-qtext').forEach(p=>{const h=p.parentElement.querySelector('h2');if(!h)return;const k=h.textContent.trim();if(copy[k])p.textContent=copy[k]})}
  new MutationObserver(apply).observe(document.getElementById('app')||document.body,{subtree:true,childList:true});
  setTimeout(apply,0);
})();
