(() => {
  const chapters = [
    ['I','A00-B99','Infektiöse und parasitäre Krankheiten',['Infektiöse Darmkrankheiten','Tuberkulose','Bakterielle Zoonosen','Sonstige bakterielle Krankheiten','Sexuell übertragbare Infektionen','Spirochätenkrankheiten','Chlamydienkrankheiten','Rickettsiosen','Virusinfektionen des Zentralnervensystems','Arthropodenübertragene Viruskrankheiten und virale hämorrhagische Fieber','Virusinfektionen der Haut und Schleimhäute','Virushepatitis','HIV-Krankheit','Sonstige Viruskrankheiten','Mykosen','Protozoenkrankheiten','Helminthosen','Läuse-, Milben- und sonstiger Parasitenbefall','Folgezustände infektiöser Krankheiten','Infektionserreger als Ursache anderswo klassifizierter Krankheiten','Sonstige Infektionskrankheiten']],
    ['II','C00-D48','Neubildungen',['Bösartige Neubildungen','In-situ-Neubildungen','Gutartige Neubildungen','Neubildungen unsicheren oder unbekannten Verhaltens']],
    ['III','D50-D90','Krankheiten des Blutes und der blutbildenden Organe / Immunsystem',['Alimentäre Anämien','Hämolytische Anämien','Aplastische und sonstige Anämien','Koagulopathien und hämorrhagische Diathesen','Sonstige Krankheiten des Blutes','Störungen mit Beteiligung des Immunsystems']],
    ['IV','E00-E90','Endokrine, Ernährungs- und Stoffwechselkrankheiten',['Schilddrüsenerkrankungen','Diabetes mellitus','Störungen der Blutglukoseregulation','Krankheiten sonstiger endokriner Drüsen','Mangelernährung','Sonstige Mangelzustände','Adipositas und sonstige Überernährung','Stoffwechselstörungen']],
    ['V','F00-F99','Psychische und Verhaltensstörungen',['Organische psychische Störungen','Störungen durch psychotrope Substanzen','Schizophrenie, schizotype und wahnhafte Störungen','Affektive Störungen','Neurotische, Belastungs- und somatoforme Störungen','Verhaltensauffälligkeiten mit körperlichen Störungen','Persönlichkeits- und Verhaltensstörungen','Intelligenzstörungen','Entwicklungsstörungen','Verhaltens- und emotionale Störungen in Kindheit und Jugend','Nicht näher bezeichnete psychische Störungen']],
    ['VI','G00-G99','Krankheiten des Nervensystems',['Entzündliche Krankheiten des ZNS','Systematrophien des ZNS','Extrapyramidale Krankheiten und Bewegungsstörungen','Degenerative Krankheiten des Nervensystems','Demyelinisierende Krankheiten des ZNS','Episodische und paroxysmale Krankheiten','Krankheiten von Nerven, Nervenwurzeln und Plexus','Polyneuropathien','Neuromuskuläre Synapse und Muskelerkrankungen','Zerebrale Lähmung und Lähmungssyndrome','Sonstige Krankheiten des Nervensystems']],
    ['VII','H00-H59','Krankheiten des Auges und der Augenanhangsgebilde',['Augenlid, Tränenapparat und Orbita','Konjunktiva','Sklera, Hornhaut, Iris und Ziliarkörper','Linse','Aderhaut und Netzhaut','Glaukom','Glaskörper und Augapfel','Sehnerv und Sehbahn','Augenmuskeln und Blickbewegungen','Sehstörungen und Blindheit','Sonstige Augenkrankheiten']],
    ['VIII','H60-H95','Krankheiten des Ohres und des Warzenfortsatzes',['Äußeres Ohr','Mittelohr und Warzenfortsatz','Innenohr','Sonstige Krankheiten des Ohres']],
    ['IX','I00-I99','Krankheiten des Kreislaufsystems',['Akutes rheumatisches Fieber','Chronische rheumatische Herzkrankheiten','Hypertonie','Ischämische Herzkrankheiten','Pulmonale Herzkrankheit und Lungenkreislauf','Sonstige Herzkrankheiten','Zerebrovaskuläre Krankheiten','Arterien, Arteriolen und Kapillaren','Venen, Lymphgefäße und Lymphknoten','Sonstige Kreislauferkrankungen']],
    ['X','J00-J99','Krankheiten des Atmungssystems',['Akute Infektionen der oberen Atemwege','Grippe und Pneumonie','Akute Infektionen der unteren Atemwege','Sonstige Krankheiten der oberen Atemwege','Chronische Krankheiten der unteren Atemwege','Lungenkrankheiten durch exogene Substanzen','Interstitielle Lungenerkrankungen','Purulente und nekrotisierende Erkrankungen der unteren Atemwege','Pleuraerkrankungen','Sonstige Krankheiten des Atmungssystems']],
    ['XI','K00-K93','Krankheiten des Verdauungssystems',['Mundhöhle, Speicheldrüsen und Kiefer','Ösophagus, Magen und Duodenum','Appendixkrankheiten','Hernien','Nichtinfektiöse Enteritis und Kolitis','Sonstige Darmkrankheiten','Peritoneum','Leberkrankheiten','Gallenblase, Gallenwege und Pankreas','Sonstige Krankheiten des Verdauungssystems']],
    ['XII','L00-L99','Krankheiten der Haut und der Unterhaut',['Infektionen der Haut und Unterhaut','Bullöse Dermatosen','Dermatitis und Ekzem','Papulosquamöse Hautkrankheiten','Urtikaria und Erytheme','Strahlenbedingte Hautkrankheiten','Krankheiten der Hautanhangsgebilde','Sonstige Hautkrankheiten']],
    ['XIII','M00-M99','Krankheiten des Muskel-Skelett-Systems und des Bindegewebes',['Arthropathien','Systemkrankheiten des Bindegewebes','Wirbelsäule und Rücken','Muskelerkrankungen','Sehnen- und Synovialerkrankungen','Sonstige Weichteilgewebserkrankungen','Osteopathien','Chondropathien','Sonstige Krankheiten des Muskel-Skelett-Systems']],
    ['XIV','N00-N99','Krankheiten des Urogenitalsystems',['Glomeruläre Nierenkrankheiten','Tubulointerstitielle Nierenkrankheiten','Niereninsuffizienz','Urolithiasis','Sonstige Nieren- und Uretererkrankungen','Harnwegserkrankungen','Männliche Genitalorgane','Mamma','Entzündliche Krankheiten der weiblichen Beckenorgane','Nichtentzündliche Krankheiten des weiblichen Genitaltraktes','Sonstige Urogenitalerkrankungen']],
    ['XV','O00-O99','Schwangerschaft, Geburt und Wochenbett',['Schwangerschaft mit abortivem Ausgang','Schwangerschaftsdauer','Ödeme, Proteinurie und Hypertonie in Schwangerschaft/Geburt/Wochenbett','Sonstige schwangerschaftsbezogene Erkrankungen der Mutter','Betreuung der Mutter hinsichtlich Fetus und Amnionhöhle','Komplikationen von Wehentätigkeit und Entbindung','Entbindung','Komplikationen im Wochenbett','Sonstige Zustände während der Gestationsperiode']],
    ['XVI','P00-P96','Bestimmte Zustände mit Ursprung in der Perinatalperiode',['Schädigung von Fetus und Neugeborenen durch mütterliche Faktoren','Störungen von Schwangerschaftsdauer und fetalem Wachstum','Geburtstrauma','Respiratorische und kardiovaskuläre Erkrankungen der Perinatalperiode','Perinatale Infektionen','Hämorrhagische und hämatologische Erkrankungen','Transitorische endokrine und Stoffwechselstörungen','Erkrankungen des Verdauungssystems beim Neugeborenen','Haut- und Temperaturregulationsstörungen','Sonstige perinatale Störungen']],
    ['XVII','Q00-Q99','Angeborene Fehlbildungen, Deformitäten und Chromosomenanomalien',['Angeborene Fehlbildungen des Nervensystems','Angeborene Fehlbildungen von Auge, Ohr, Gesicht und Hals','Angeborene Fehlbildungen des Kreislaufsystems','Angeborene Fehlbildungen des Atmungssystems','Lippen-, Kiefer- und Gaumenspalten','Angeborene Fehlbildungen des Verdauungssystems','Angeborene Fehlbildungen der Genitalorgane','Angeborene Fehlbildungen des Harnsystems','Angeborene Fehlbildungen des Muskel-Skelett-Systems','Sonstige angeborene Fehlbildungen','Chromosomenanomalien']],
    ['XVIII','R00-R99','Symptome und abnorme klinische/laborchemische Befunde',['Kreislauf- und Atmungssymptome','Verdauungs- und Abdominalsymptome','Hautsymptome','Neurologische und muskuloskelettale Symptome','Harnsystemsymptome','Erkennungs-, Wahrnehmungs-, Stimmungs- und Verhaltenssymptome','Sprach- und Stimmstörungen','Allgemeinsymptome','Abnorme Blutuntersuchungsbefunde','Abnorme Urinbefunde','Abnorme Befunde anderer Körperflüssigkeiten/Gewebe','Abnorme Befunde bei Bildgebung/Funktionsprüfung','Ungenaue und unbekannte Todesursachen']],
    ['XIX','S00-T98','Verletzungen, Vergiftungen und sonstige Folgen äußerer Ursachen',['Kopfverletzungen','Halsverletzungen','Thoraxverletzungen','Abdomen-/Becken-/LWS-Verletzungen','Schulter- und Oberarmverletzungen','Ellenbogen- und Unterarmverletzungen','Handgelenk- und Handverletzungen','Hüft- und Oberschenkelverletzungen','Knie- und Unterschenkelverletzungen','Knöchel- und Fußverletzungen','Verletzungen mehrerer Körperregionen','Fremdkörperverletzungen','Verbrennungen und Verätzungen','Erfrierungen','Vergiftungen durch Arzneimittel und Drogen','Toxische Wirkungen nichtmedizinischer Substanzen','Sonstige Schäden durch äußere Ursachen','Frühkomplikationen eines Traumas','Komplikationen medizinischer Behandlung','Spätfolgen von Verletzungen und Vergiftungen']],
    ['XX','V01-Y84','Äußere Ursachen von Morbidität und Mortalität',['Unfälle','Vorsätzliche Selbstbeschädigung','Tätlicher Angriff','Unbestimmte Ereignisse','Gesetzliche Maßnahmen und Kriegshandlungen','Komplikationen medizinischer/ chirurgischer Behandlung']],
    ['XXI','Z00-Z99','Faktoren, die den Gesundheitszustand beeinflussen',['Untersuchung und Abklärung','Potenzielle Risiken hinsichtlich übertragbarer Krankheiten','Reproduktion','Spezifische medizinische Maßnahmen und Betreuung','Sozioökonomische und psychosoziale Risiken','Sonstige Gründe der Inanspruchnahme des Gesundheitswesens','Familien-/Eigenanamnese und sonstige gesundheitsbeeinflussende Zustände']],
    ['XXII','U00-U99','Schlüsselnummern für besondere Zwecke',['Vorläufige Zuordnungen für Krankheiten unklarer Ätiologie','Funktionseinschränkung','Organtransplantationsregistrierung','Stadieneinteilung HIV-Infektion','Sekundäre Schlüsselnummern für Neubildungen','Sekundäre Schlüsselnummern für psychische und Verhaltensstörungen','Sonstige sekundäre Schlüsselnummern','Resistenzen gegen Antibiotika/Chemotherapeutika','Belegte und nicht belegte Schlüsselnummern']]
  ];
  const common = [
    ['A41','Sepsis'],['J44','COPD'],['J18','Pneumonie'],['J45','Asthma bronchiale'],['I21','Akuter Myokardinfarkt'],['I50','Herzinsuffizienz'],['I10','Arterielle Hypertonie'],['I48','Vorhofflimmern'],['I63','Hirninfarkt'],['G40','Epilepsie'],['G20','Parkinson-Krankheit'],['E10-E14','Diabetes mellitus'],['E03','Hypothyreose'],['E05','Hyperthyreose'],['K35','Akute Appendizitis'],['K80','Cholelithiasis'],['K85','Akute Pankreatitis'],['N20','Urolithiasis'],['N17','Akutes Nierenversagen'],['F32','Depressive Episode'],['F20','Schizophrenie'],['F10','Psychische/Verhaltensstörungen durch Alkohol'],['C34','Bösartige Neubildung der Bronchien/Lunge'],['C50','Bösartige Neubildung der Brustdrüse'],['C18','Bösartige Neubildung des Kolons'],['D50','Eisenmangelanämie'],['M17','Gonarthrose'],['M54','Rückenschmerz'],['L20','Atopisches Ekzem'],['B15-B19','Virushepatitis'],['O14','Präeklampsie'],['P22','Atemnotsyndrom des Neugeborenen'],['Q21','Angeborene Fehlbildungen der Herzscheidewände'],['S06','Intrakranielle Verletzung'],['T20-T32','Verbrennungen/Verätzungen']
  ];
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const items=[];
  chapters.forEach(c=>c[3].forEach(name=>items.push({chapter:c[0],range:c[1],chapterTitle:c[2],name,search:`${c[0]} ${c[1]} ${c[2]} ${name}`.toLowerCase()})));
  common.forEach(x=>items.push({chapter:'',range:x[0],chapterTitle:'Häufige Krankheitsbilder',name:x[1],search:`${x[0]} ${x[1]}`.toLowerCase(),common:true}));
  const app=document.getElementById('app');
  const nav=document.querySelector('.nav');
  if(nav && !nav.querySelector('[data-view="krankheiten"]')){const b=document.createElement('button');b.className='nav-item';b.dataset.view='krankheiten';b.innerHTML='<span>📚</span> Krankheitsbilder';nav.appendChild(b);}
  function render(q=''){
    document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view==='krankheiten'));
    const query=q.trim().toLowerCase();
    let result=query?items.filter(x=>x.search.includes(query)):items.slice(0,80);
    const groups={}; result.forEach(x=>{const k=x.common?'Häufige Krankheitsbilder':`${x.chapter} · ${x.chapterTitle}`;(groups[k]??=[]).push(x)});
    app.innerHTML=`<div class="view-title"><div><span class="eyebrow">MEDIZINISCHER KATALOG</span><h1>Krankheitsbilder</h1><p>Strukturierte Übersicht nach ICD-10-GM 2026. Suche nach Diagnose, Begriff oder Kapitel.</p></div></div><div class="panel disease-search"><div class="search" style="margin:0;max-width:none"><input id="diseaseSearch" placeholder="z. B. Sepsis, COPD, Diabetes, Herzinfarkt …" value="${esc(q)}"><span class="disease-count">${result.length} Treffer</span></div></div><div class="disease-grid">${Object.entries(groups).map(([g,arr])=>`<section class="panel disease-group"><div class="panel-title">${esc(g)}</div>${arr.map(x=>`<div class="disease-row"><span class="disease-code">${esc(x.range)}</span><div><strong>${esc(x.name)}</strong><small>${esc(x.chapterTitle)}</small></div></div>`).join('')}</section>`).join('')}</div><div class="notice"><strong>Hinweis:</strong> Der Katalog dient als Such-/Orientierungshilfe. Die verbindliche Klassifikation und aktuelle Detailinformationen stehen in der offiziellen BfArM-Fassung 2026.</div><div class="disease-source"><a href="https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2026/index.htm" target="_blank" rel="noopener">↗ Offizielle ICD-10-GM 2026 bei BfArM öffnen</a></div>`;
    document.getElementById('diseaseSearch').addEventListener('input',e=>render(e.target.value));
  }
  document.addEventListener('click',e=>{const b=e.target.closest('[data-view="krankheiten"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();render();},true);
  render();
})();