(()=> {
  if(window.__rdKrankheitslexikonPlus)return;
  window.__rdKrankheitslexikonPlus=true;
  const DATA=[{"id":"dx-0000","name":"Sepsis","category":"Infektiologie","code":"A41","aliases":"Blutvergiftung","summary":"Sepsis ist ein Krankheitsbild aus dem Bereich Infektiologie.","focus":"Infektiöse Erkrankung; Fokus auf Infektionszeichen, Verlauf, Exposition und mögliche systemische Beteiligung.","redFlags":"Auffällige Vitalparameter, Bewusstseinsänderung oder rasche Verschlechterung ernst nehmen.","education":"Für Ausbildung/Strukturierung: Anamnese, klinische Untersuchung, Verlauf und relevante Befunde systematisch erfassen.","source":"ICD-10-GM 2026 Kapitel-/Kodierungsstruktur und kuratierte Ausbildungsbegriffe"}];
  // Additional entries are loaded from the generated data payload below.
  const EXTRA=window.RD_KRANKHEITSLEXIKON_EXTRA||[];
  DATA.push(...EXTRA);
  const app=document.getElementById('app');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const uniq=arr=>[...new Set(arr.filter(Boolean))];
  const CATS=['Alle',...uniq(DATA.map(x=>x.category))];
  function nav(){const old=document.querySelector('.nav-item[data-view="krankheiten"]');if(old){old.dataset.view='krankheiten-plus';old.innerHTML='<span class="nav-icon">📚</span><span class="nav-label">Krankheitsbilder</span>';}const navEl=document.querySelector('.nav');if(navEl&&!navEl.querySelector('[data-view="krankheiten-plus"]')){const b=document.createElement('button');b.className='nav-item';b.dataset.view='krankheiten-plus';b.innerHTML='<span class="nav-icon">📚</span><span class="nav-label">Krankheitsbilder</span>';navEl.appendChild(b);}}
  function render(query='',cat='Alle'){
    nav();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view==='krankheiten-plus'));
    const q=query.trim().toLowerCase();const list=DATA.filter(x=>(cat==='Alle'||x.category===cat)&&(!q||`${x.name} ${x.code} ${x.category} ${x.aliases}`.toLowerCase().includes(q)));
    app.innerHTML=`<div class="view-title disease-plus-hero"><div><span class="eyebrow red">MEDIZINISCHES KRANKHEITSLEXIKON</span><h1>Krankheitsbilder &amp; Erkrankungen</h1><p>Umfassender Offline-Katalog mit ${DATA.length} benannten Krankheitsbildern. Suche nach Diagnose, ICD-Code, Synonym oder Fachbereich.</p></div></div><section class="disease-plus-toolbar panel"><div class="disease-plus-search"><input id="dxSearch" value="${esc(query)}" placeholder="z. B. Sepsis, Herzinfarkt, COPD, Meningitis, Eklampsie …" autocomplete="off"></div><select id="dxCategory">${CATS.map(c=>`<option value="${esc(c)}" ${c===cat?'selected':''}>${esc(c)}</option>`).join('')}</select><button class="suite-btn primary" id="dxReset">Zurücksetzen</button><div class="disease-plus-meta">${list.length} Treffer · ${DATA.length} Einträge</div></section><section class="disease-plus-source panel"><div><strong>Quelle &amp; Zweck</strong><span>ICD-10-GM 2026 als Klassifikationsrahmen; ergänzend kuratierte benannte Krankheitsbilder für Ausbildung und schnelle Orientierung.</span></div><a href="https://klassifikationen.bfarm.de/icd-10-gm/kode-suche/htmlgm2026/index.htm" target="_blank" rel="noopener noreferrer">BfArM ICD-10-GM 2026 ↗</a></section><section id="dxResults" class="disease-plus-grid">${list.map(x=>`<article class="disease-plus-card" tabindex="0" data-id="${x.id}"><div class="disease-plus-top"><span class="disease-plus-cat">${esc(x.category)}</span>${x.code?`<span class="disease-plus-code">${esc(x.code)}</span>`:''}</div><h2>${esc(x.name)}</h2><p>${esc(x.summary)}</p><div class="disease-plus-actions"><button class="suite-btn" data-dx-open="${x.id}">Details</button></div></article>`).join('')||'<div class="suite-note">Keine Treffer. Suchbegriff oder Fachbereich ändern.</div>'}</section><div class="modal hidden" id="dxModal" role="dialog" aria-modal="true" aria-labelledby="dxTitle"><div class="modal-card disease-plus-modal"><div class="modal-head"><div><span class="eyebrow red">KRANKHEITSBILD</span><h2 id="dxTitle"></h2></div><button class="close" id="dxClose" aria-label="Schließen">×</button></div><div id="dxBody"></div></div></div>`;
    const open=id=>{const x=DATA.find(d=>d.id===id);if(!x)return;document.getElementById('dxTitle').textContent=x.name;document.getElementById('dxBody').innerHTML=`<div class="dx-detail-grid"><div class="dx-detail-item"><small>Fachbereich</small><strong>${esc(x.category)}</strong></div><div class="dx-detail-item"><small>ICD-10-GM</small><strong>${esc(x.code||'—')}</strong></div></div><div class="dx-detail-block"><h3>Kurzübersicht</h3><p>${esc(x.summary)}</p></div><div class="dx-detail-block"><h3>Worauf achten?</h3><p>${esc(x.focus)}</p></div><div class="dx-detail-block"><h3>Warnzeichen</h3><p>${esc(x.redFlags)}</p></div><div class="dx-detail-block"><h3>Ausbildungsfokus</h3><p>${esc(x.education)}</p></div><div class="dx-detail-block"><h3>Suchbegriffe</h3><p>${esc(x.aliases||x.name)}</p></div><div class="suite-note">Ausbildungs-/Orientierungsinhalt. Keine individuelle Diagnose oder Therapieanweisung; lokale SOPs, Leitlinien und ärztliche Anordnungen haben Vorrang. Quelle: ${esc(x.source)}.</div>`;document.getElementById('dxModal').classList.remove('hidden');};
    document.getElementById('dxSearch').addEventListener('input',e=>render(e.target.value,document.getElementById('dxCategory').value));document.getElementById('dxCategory').addEventListener('change',e=>render(document.getElementById('dxSearch').value,e.target.value));document.getElementById('dxReset').addEventListener('click',()=>render());document.getElementById('dxResults').addEventListener('click',e=>{const b=e.target.closest('[data-dx-open]');if(b)open(b.dataset.dxOpen);});document.getElementById('dxResults').addEventListener('keydown',e=>{if(e.key==='Enter'){const card=e.target.closest('.disease-plus-card');if(card)open(card.dataset.id);}});document.getElementById('dxClose').addEventListener('click',()=>document.getElementById('dxModal').classList.add('hidden'));document.getElementById('dxModal').addEventListener('click',e=>{if(e.target.id==='dxModal')e.target.classList.add('hidden');});
  }
  window.renderKrankheitenPlus=(q='',cat='Alle')=>render(q,cat);nav();window.addEventListener('click',e=>{const b=e.target.closest?.('.nav-item[data-view="krankheiten-plus"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();render();document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===b));const crumb=document.getElementById('breadcrumbCurrent');if(crumb)crumb.textContent='Krankheitsbilder';},true);
})();